// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ID is an autogenerated mock type for the ID type
type ID struct {
	mock.Mock
}

// IsNil provides a mock function with given fields:
func (_m *ID) IsNil() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewID interface {
	mock.TestingT
	Cleanup(func())
}

// NewID creates a new instance of ID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewID(t mockConstructorTestingTNewID) *ID {
	mock := &ID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
