// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BadaasID is an autogenerated mock type for the BadaasID type
type BadaasID struct {
	mock.Mock
}

type mockConstructorTestingTNewBadaasID interface {
	mock.TestingT
	Cleanup(func())
}

// NewBadaasID creates a new instance of BadaasID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBadaasID(t mockConstructorTestingTNewBadaasID) *BadaasID {
	mock := &BadaasID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
