// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	orm "github.com/ditrit/badaas/orm"
	mock "github.com/stretchr/testify/mock"
)

// IJoinCondition is an autogenerated mock type for the IJoinCondition type
type IJoinCondition[T orm.Model] struct {
	mock.Mock
}

// ApplyTo provides a mock function with given fields: query, table
func (_m *IJoinCondition[T]) ApplyTo(query *orm.Query, table orm.Table) error {
	ret := _m.Called(query, table)

	var r0 error
	if rf, ok := ret.Get(0).(func(*orm.Query, orm.Table) error); ok {
		r0 = rf(query, table)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InterfaceVerificationMethod provides a mock function with given fields: _a0
func (_m *IJoinCondition[T]) InterfaceVerificationMethod(_a0 T) {
	_m.Called(_a0)
}

// makesFilter provides a mock function with given fields:
func (_m *IJoinCondition[T]) makesFilter() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// makesPreload provides a mock function with given fields:
func (_m *IJoinCondition[T]) makesPreload() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewIJoinCondition interface {
	mock.TestingT
	Cleanup(func())
}

// NewIJoinCondition creates a new instance of IJoinCondition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIJoinCondition[T orm.Model](t mockConstructorTestingTNewIJoinCondition) *IJoinCondition[T] {
	mock := &IJoinCondition[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
