// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	orm "github.com/ditrit/badaas/orm"
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// WhereCondition is an autogenerated mock type for the WhereCondition type
type WhereCondition[T orm.Model] struct {
	mock.Mock
}

// ApplyTo provides a mock function with given fields: query, table
func (_m *WhereCondition[T]) ApplyTo(query *gorm.DB, table orm.Table) (*gorm.DB, error) {
	ret := _m.Called(query, table)

	var r0 *gorm.DB
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, orm.Table) (*gorm.DB, error)); ok {
		return rf(query, table)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, orm.Table) *gorm.DB); ok {
		r0 = rf(query, table)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, orm.Table) error); ok {
		r1 = rf(query, table)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSQL provides a mock function with given fields: query, table
func (_m *WhereCondition[T]) GetSQL(query *gorm.DB, table orm.Table) (string, []interface{}, error) {
	ret := _m.Called(query, table)

	var r0 string
	var r1 []interface{}
	var r2 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, orm.Table) (string, []interface{}, error)); ok {
		return rf(query, table)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, orm.Table) string); ok {
		r0 = rf(query, table)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, orm.Table) []interface{}); ok {
		r1 = rf(query, table)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]interface{})
		}
	}

	if rf, ok := ret.Get(2).(func(*gorm.DB, orm.Table) error); ok {
		r2 = rf(query, table)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// affectsDeletedAt provides a mock function with given fields:
func (_m *WhereCondition[T]) affectsDeletedAt() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// interfaceVerificationMethod provides a mock function with given fields: _a0
func (_m *WhereCondition[T]) interfaceVerificationMethod(_a0 T) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewWhereCondition interface {
	mock.TestingT
	Cleanup(func())
}

// NewWhereCondition creates a new instance of WhereCondition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWhereCondition[T orm.Model](t mockConstructorTestingTNewWhereCondition) *WhereCondition[T] {
	mock := &WhereCondition[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
