// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	models "github.com/ditrit/badaas/testintegration/models"
	"time"
)

func BicycleId(operator orm.Operator[orm.UUID]) orm.WhereCondition[models.Bicycle] {
	return orm.FieldCondition[models.Bicycle, orm.UUID]{
		Field:    "ID",
		Operator: operator,
	}
}
func BicycleCreatedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.Bicycle] {
	return orm.FieldCondition[models.Bicycle, time.Time]{
		Field:    "CreatedAt",
		Operator: operator,
	}
}
func BicycleUpdatedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.Bicycle] {
	return orm.FieldCondition[models.Bicycle, time.Time]{
		Field:    "UpdatedAt",
		Operator: operator,
	}
}
func BicycleDeletedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.Bicycle] {
	return orm.FieldCondition[models.Bicycle, time.Time]{
		Field:    "DeletedAt",
		Operator: operator,
	}
}
func BicycleName(operator orm.Operator[string]) orm.WhereCondition[models.Bicycle] {
	return orm.FieldCondition[models.Bicycle, string]{
		Field:    "Name",
		Operator: operator,
	}
}
func BicycleOwner(conditions ...orm.Condition[models.Person]) orm.Condition[models.Bicycle] {
	return orm.JoinCondition[models.Bicycle, models.Person]{
		Conditions:    conditions,
		RelationField: "Owner",
		T1Field:       "OwnerName",
		T2Field:       "Name",
	}
}
func BicycleOwnerName(operator orm.Operator[string]) orm.WhereCondition[models.Bicycle] {
	return orm.FieldCondition[models.Bicycle, string]{
		Field:    "OwnerName",
		Operator: operator,
	}
}
