// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	models "github.com/ditrit/badaas/testintegration/models"
	"time"
)

func BrandId(operator orm.Operator[uint]) orm.WhereCondition[models.Brand] {
	return orm.FieldCondition[models.Brand, uint]{
		FieldIdentifier: orm.IDFieldID,
		Operator:        operator,
	}
}
func BrandCreatedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.Brand] {
	return orm.FieldCondition[models.Brand, time.Time]{
		FieldIdentifier: orm.CreatedAtFieldID,
		Operator:        operator,
	}
}
func BrandUpdatedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.Brand] {
	return orm.FieldCondition[models.Brand, time.Time]{
		FieldIdentifier: orm.UpdatedAtFieldID,
		Operator:        operator,
	}
}
func BrandDeletedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.Brand] {
	return orm.FieldCondition[models.Brand, time.Time]{
		FieldIdentifier: orm.DeletedAtFieldID,
		Operator:        operator,
	}
}

var brandNameFieldID = orm.FieldIdentifier{Field: "Name"}

func BrandName(operator orm.Operator[string]) orm.WhereCondition[models.Brand] {
	return orm.FieldCondition[models.Brand, string]{
		FieldIdentifier: brandNameFieldID,
		Operator:        operator,
	}
}
