// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	models "github.com/ditrit/badaas/testintegration/models"
	"time"
)

func CompanyId(operator orm.Operator[orm.UUID]) orm.WhereCondition[models.Company] {
	return orm.FieldCondition[models.Company, orm.UUID]{
		Field:    "ID",
		Operator: operator,
	}
}
func CompanyCreatedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.Company] {
	return orm.FieldCondition[models.Company, time.Time]{
		Field:    "CreatedAt",
		Operator: operator,
	}
}
func CompanyUpdatedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.Company] {
	return orm.FieldCondition[models.Company, time.Time]{
		Field:    "UpdatedAt",
		Operator: operator,
	}
}
func CompanyDeletedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.Company] {
	return orm.FieldCondition[models.Company, time.Time]{
		Field:    "DeletedAt",
		Operator: operator,
	}
}
func CompanyName(operator orm.Operator[string]) orm.WhereCondition[models.Company] {
	return orm.FieldCondition[models.Company, string]{
		Field:    "Name",
		Operator: operator,
	}
}
func SellerCompany(conditions ...orm.Condition[models.Company]) orm.Condition[models.Seller] {
	return orm.JoinCondition[models.Seller, models.Company]{
		Conditions: conditions,
		T1Field:    "CompanyID",
		T2Field:    "ID",
	}
}
