// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func EmployeeId(v orm.UUID) orm.WhereCondition[models.Employee] {
	return orm.WhereCondition[models.Employee]{
		Field: "ID",
		Value: v,
	}
}
func EmployeeCreatedAt(v time.Time) orm.WhereCondition[models.Employee] {
	return orm.WhereCondition[models.Employee]{
		Field: "CreatedAt",
		Value: v,
	}
}
func EmployeeUpdatedAt(v time.Time) orm.WhereCondition[models.Employee] {
	return orm.WhereCondition[models.Employee]{
		Field: "UpdatedAt",
		Value: v,
	}
}
func EmployeeDeletedAt(v gorm.DeletedAt) orm.WhereCondition[models.Employee] {
	return orm.WhereCondition[models.Employee]{
		Field: "DeletedAt",
		Value: v,
	}
}
func EmployeeName(v string) orm.WhereCondition[models.Employee] {
	return orm.WhereCondition[models.Employee]{
		Field: "Name",
		Value: v,
	}
}
func EmployeeBoss(conditions ...orm.Condition[models.Employee]) orm.Condition[models.Employee] {
	return orm.JoinCondition[models.Employee, models.Employee]{
		Conditions: conditions,
		T1Field:    "BossID",
		T2Field:    "ID",
	}
}
func EmployeeBossId(v orm.UUID) orm.WhereCondition[models.Employee] {
	return orm.WhereCondition[models.Employee]{
		Field: "BossID",
		Value: v,
	}
}
