// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	model "github.com/ditrit/badaas/orm/model"
	models "github.com/ditrit/badaas/testintegration/models"
	"time"
)

type parentParentConditions struct {
	ID        orm.Field[models.ParentParent, model.UUID]
	CreatedAt orm.Field[models.ParentParent, time.Time]
	UpdatedAt orm.Field[models.ParentParent, time.Time]
	DeletedAt orm.Field[models.ParentParent, time.Time]
	Name      orm.StringField[models.ParentParent]
	Number    orm.Field[models.ParentParent, int]
}

var ParentParent = parentParentConditions{
	CreatedAt: orm.Field[models.ParentParent, time.Time]{Name: "CreatedAt"},
	DeletedAt: orm.Field[models.ParentParent, time.Time]{Name: "DeletedAt"},
	ID:        orm.Field[models.ParentParent, model.UUID]{Name: "ID"},
	Name:      orm.StringField[models.ParentParent]{Field: orm.Field[models.ParentParent, string]{Name: "Name"}},
	Number:    orm.Field[models.ParentParent, int]{Name: "Number"},
	UpdatedAt: orm.Field[models.ParentParent, time.Time]{Name: "UpdatedAt"},
}

// Preload allows preloading the ParentParent when doing a query
func (parentParentConditions parentParentConditions) Preload() orm.Condition[models.ParentParent] {
	return orm.NewPreloadCondition[models.ParentParent](parentParentConditions.ID, parentParentConditions.CreatedAt, parentParentConditions.UpdatedAt, parentParentConditions.DeletedAt, parentParentConditions.Name, parentParentConditions.Number)
}
