// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func ParentParentId(operator orm.Operator[orm.UUID]) orm.WhereCondition[models.ParentParent] {
	return orm.FieldCondition[models.ParentParent, orm.UUID]{
		FieldIdentifier: orm.IDFieldID,
		Operator:        operator,
	}
}
func ParentParentCreatedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.ParentParent] {
	return orm.FieldCondition[models.ParentParent, time.Time]{
		FieldIdentifier: orm.CreatedAtFieldID,
		Operator:        operator,
	}
}
func ParentParentUpdatedAt(operator orm.Operator[time.Time]) orm.WhereCondition[models.ParentParent] {
	return orm.FieldCondition[models.ParentParent, time.Time]{
		FieldIdentifier: orm.UpdatedAtFieldID,
		Operator:        operator,
	}
}
func ParentParentDeletedAt(operator orm.Operator[gorm.DeletedAt]) orm.WhereCondition[models.ParentParent] {
	return orm.FieldCondition[models.ParentParent, gorm.DeletedAt]{
		FieldIdentifier: orm.DeletedAtFieldID,
		Operator:        operator,
	}
}

var parentParentNameFieldID = orm.FieldIdentifier{Field: "Name"}

func ParentParentName(operator orm.Operator[string]) orm.WhereCondition[models.ParentParent] {
	return orm.FieldCondition[models.ParentParent, string]{
		FieldIdentifier: parentParentNameFieldID,
		Operator:        operator,
	}
}

var ParentParentPreloadAttributes = orm.NewPreloadCondition[models.ParentParent](parentParentNameFieldID)
