// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	models "github.com/ditrit/badaas/testintegration/models"
	gorm "gorm.io/gorm"
	"time"
)

func PhoneId(v uint) orm.WhereCondition[models.Phone] {
	return orm.WhereCondition[models.Phone]{
		Field: "ID",
		Value: v,
	}
}
func PhoneCreatedAt(v time.Time) orm.WhereCondition[models.Phone] {
	return orm.WhereCondition[models.Phone]{
		Field: "CreatedAt",
		Value: v,
	}
}
func PhoneUpdatedAt(v time.Time) orm.WhereCondition[models.Phone] {
	return orm.WhereCondition[models.Phone]{
		Field: "UpdatedAt",
		Value: v,
	}
}
func PhoneDeletedAt(v gorm.DeletedAt) orm.WhereCondition[models.Phone] {
	return orm.WhereCondition[models.Phone]{
		Field: "DeletedAt",
		Value: v,
	}
}
func PhoneName(v string) orm.WhereCondition[models.Phone] {
	return orm.WhereCondition[models.Phone]{
		Field: "Name",
		Value: v,
	}
}
func PhoneBrand(conditions ...orm.Condition[models.Brand]) orm.Condition[models.Phone] {
	return orm.JoinCondition[models.Phone, models.Brand]{
		Conditions: conditions,
		T1Field:    "BrandID",
		T2Field:    "ID",
	}
}
func PhoneBrandId(v uint) orm.WhereCondition[models.Phone] {
	return orm.WhereCondition[models.Phone]{
		Field: "BrandID",
		Value: v,
	}
}
