version: '3.5'

services:
  db:
    image: cockroachdb/cockroach:latest
    ports:
      - "26257:26257"
      - "8080:8080" # Web based dashboard
    command: start-single-node --insecure
    volumes:
      - "${PWD}/_temp/cockroach-data/crdb:/cockroach/cockroach-data"


  api:
    build: ditrit/badaas:latest # local image
    ports:
      - "8000:8000"
    depends_on:
      - db
