# DEVELOPMENT ONLY, DO NOT USE FOR PRODUCTION
version: '3.5'

services:
  db:
    container_name: "cql-test-db"
    image: postgres:latest
    environment:
      POSTGRES_USER: cql
      POSTGRES_PASSWORD: cql_password2023
      POSTGRES_DB: cql_db
      PGDATA: /data/postgres
    ports:
      - "5000:5432"
    volumes:
      - .:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5