database:
  host: badaas-db
  name: badaas_db
  password: postgres
  sslmode: disable
  username: root
  port: 26257
  init:
    retry: 10
    retryTime: 5
server:
  host: ""
  port: 8000
  timeout: 15
  pagination:
    page:
      max: 100
logger:
  mode: prod
  request:
    template: "Receive {{method}} request on {{url}}"
session:
  duration: 14400
  pullInterval: 30
  rollDuration: 3600
default:
  admin:
    password: admin