// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	cql "github.com/ditrit/badaas/orm/cql"
	mock "github.com/stretchr/testify/mock"

	model "github.com/ditrit/badaas/orm/model"
)

// Condition is an autogenerated mock type for the Condition type
type Condition[T model.Model] struct {
	mock.Mock
}

// ApplyTo provides a mock function with given fields: _a0, _a1
func (_m *Condition[T]) ApplyTo(_a0 *cql.GormQuery, _a1 cql.Table) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cql.GormQuery, cql.Table) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InterfaceVerificationMethod provides a mock function with given fields: _a0
func (_m *Condition[T]) InterfaceVerificationMethod(_a0 T) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewCondition interface {
	mock.TestingT
	Cleanup(func())
}

// NewCondition creates a new instance of Condition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCondition[T model.Model](t mockConstructorTestingTNewCondition) *Condition[T] {
	mock := &Condition[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
