// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	cql "github.com/ditrit/badaas/orm/cql"
	mock "github.com/stretchr/testify/mock"

	reflect "reflect"
)

// IField is an autogenerated mock type for the IField type
type IField struct {
	mock.Mock
}

// ColumnName provides a mock function with given fields: query, table
func (_m *IField) ColumnName(query *cql.GormQuery, table cql.Table) string {
	ret := _m.Called(query, table)

	var r0 string
	if rf, ok := ret.Get(0).(func(*cql.GormQuery, cql.Table) string); ok {
		r0 = rf(query, table)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ColumnSQL provides a mock function with given fields: query, table
func (_m *IField) ColumnSQL(query *cql.GormQuery, table cql.Table) string {
	ret := _m.Called(query, table)

	var r0 string
	if rf, ok := ret.Get(0).(func(*cql.GormQuery, cql.Table) string); ok {
		r0 = rf(query, table)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// FieldName provides a mock function with given fields:
func (_m *IField) FieldName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetModelType provides a mock function with given fields:
func (_m *IField) GetModelType() reflect.Type {
	ret := _m.Called()

	var r0 reflect.Type
	if rf, ok := ret.Get(0).(func() reflect.Type); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.Type)
		}
	}

	return r0
}

type mockConstructorTestingTNewIField interface {
	mock.TestingT
	Cleanup(func())
}

// NewIField creates a new instance of IField. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIField(t mockConstructorTestingTNewIField) *IField {
	mock := &IField{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
