// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	model "github.com/ditrit/badaas/orm/model"
	mock "github.com/stretchr/testify/mock"

	query "github.com/ditrit/badaas/orm/query"
)

// JoinCondition is an autogenerated mock type for the JoinCondition type
type JoinCondition[T model.Model] struct {
	mock.Mock
}

// ApplyTo provides a mock function with given fields: _a0, _a1
func (_m *JoinCondition[T]) ApplyTo(_a0 *query.Query, _a1 query.Table) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*query.Query, query.Table) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InterfaceVerificationMethod provides a mock function with given fields: _a0
func (_m *JoinCondition[T]) InterfaceVerificationMethod(_a0 T) {
	_m.Called(_a0)
}

// makesFilter provides a mock function with given fields:
func (_m *JoinCondition[T]) makesFilter() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// makesPreload provides a mock function with given fields:
func (_m *JoinCondition[T]) makesPreload() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewJoinCondition interface {
	mock.TestingT
	Cleanup(func())
}

// NewJoinCondition creates a new instance of JoinCondition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJoinCondition[T model.Model](t mockConstructorTestingTNewJoinCondition) *JoinCondition[T] {
	mock := &JoinCondition[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
