// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MiddlewareLogger is an autogenerated mock type for the MiddlewareLogger type
type MiddlewareLogger struct {
	mock.Mock
}

// Handle provides a mock function with given fields: next
func (_m *MiddlewareLogger) Handle(next http.Handler) http.Handler {
	ret := _m.Called(next)

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

type mockConstructorTestingTNewMiddlewareLogger interface {
	mock.TestingT
	Cleanup(func())
}

// NewMiddlewareLogger creates a new instance of MiddlewareLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMiddlewareLogger(t mockConstructorTestingTNewMiddlewareLogger) *MiddlewareLogger {
	mock := &MiddlewareLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
