// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/tests/models"
	"time"
)

type accountConditions struct {
	ID        condition.Field[models.Account, model.UIntID]
	CreatedAt condition.Field[models.Account, time.Time]
	UpdatedAt condition.Field[models.Account, time.Time]
	DeletedAt condition.Field[models.Account, time.Time]
	UserID    condition.NullableNumericField[models.Account, int64]
	Number    condition.StringField[models.Account]
}

var Account = accountConditions{
	CreatedAt: condition.NewField[models.Account, time.Time]("CreatedAt", "", ""),
	DeletedAt: condition.NewField[models.Account, time.Time]("DeletedAt", "", ""),
	ID:        condition.NewField[models.Account, model.UIntID]("ID", "", ""),
	Number:    condition.NewStringField[models.Account]("Number", "", ""),
	UpdatedAt: condition.NewField[models.Account, time.Time]("UpdatedAt", "", ""),
	UserID:    condition.NewNullableNumericField[models.Account, int64]("UserID", "", ""),
}

// Preload allows preloading the Account when doing a query
func (accountConditions accountConditions) preload() condition.Condition[models.Account] {
	return condition.NewPreloadCondition[models.Account](accountConditions.ID, accountConditions.CreatedAt, accountConditions.UpdatedAt, accountConditions.DeletedAt, accountConditions.UserID, accountConditions.Number)
}
