// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/tests/models"
	gorm "gorm.io/gorm"
	"time"
)

var accountScanner = &condition.Scanner[models.Account]{
	AssignValues: func(dest *models.Account, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = model.UIntID(v.Int64)
			case "created_at":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner created_at: bad type %T", values[i])
				}
				if v.Valid {
					dest.CreatedAt = v.Time
				}
			case "updated_at":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner updated_at: bad type %T", values[i])
				}
				if v.Valid {
					dest.UpdatedAt = v.Time
				}
			case "deleted_at":
				v, ok := values[i].(*gorm.DeletedAt)
				if !ok {
					return fmt.Errorf("cql scanner deleted_at: bad type %T", values[i])
				}
				dest.DeletedAt = *v
			case "user_id":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner user_id: bad type %T", values[i])
				}
				dest.UserID = *v
			case "number":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner number: bad type %T", values[i])
				}
				if v.Valid {
					dest.Number = v.String
				}
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "created_at":
				if v, ok := values[i].(*sql.NullTime); ok {
					condition.ReleaseNullTime(v)
				}
			case "updated_at":
				if v, ok := values[i].(*sql.NullTime); ok {
					condition.ReleaseNullTime(v)
				}
			case "deleted_at":
				if v, ok := values[i].(*gorm.DeletedAt); ok {
					condition.ReleaseDeletedAt(v)
				}
			case "user_id":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "number":
				if v, ok := values[i].(*sql.NullString); ok {
					condition.ReleaseNullString(v)
				}
			default:
				if v, ok := values[i].(*condition.NullSink); ok {
					condition.ReleaseNullSink(v)
				}
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireNullInt64()
			case "created_at":
				values[i] = condition.AcquireNullTime()
			case "updated_at":
				values[i] = condition.AcquireNullTime()
			case "deleted_at":
				values[i] = condition.AcquireDeletedAt()
			case "user_id":
				values[i] = condition.AcquireNullInt64()
			case "number":
				values[i] = condition.AcquireNullString()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}

func init() {
	condition.RegisterScanner(accountScanner)
	Account.ID = condition.NewField[models.Account, model.UIntID]("ID", "", "", accountScanner)
	Account.CreatedAt = condition.NewField[models.Account, time.Time]("CreatedAt", "", "", accountScanner)
	Account.UpdatedAt = condition.NewField[models.Account, time.Time]("UpdatedAt", "", "", accountScanner)
	Account.DeletedAt = condition.NewField[models.Account, time.Time]("DeletedAt", "", "", accountScanner)
	Account.UserID = condition.NewNullableNumericField[models.Account, int64]("UserID", "", "", accountScanner)
	Account.Number = condition.NewStringField[models.Account]("Number", "", "", accountScanner)
}
