// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/tests/models"
	gorm "gorm.io/gorm"
	"time"
)

var petScanner = &condition.Scanner[models.Pet]{
	AssignValues: func(dest *models.Pet, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = model.UIntID(v.Int64)
			case "created_at":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner created_at: bad type %T", values[i])
				}
				if v.Valid {
					dest.CreatedAt = v.Time
				}
			case "updated_at":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner updated_at: bad type %T", values[i])
				}
				if v.Valid {
					dest.UpdatedAt = v.Time
				}
			case "deleted_at":
				v, ok := values[i].(*gorm.DeletedAt)
				if !ok {
					return fmt.Errorf("cql scanner deleted_at: bad type %T", values[i])
				}
				dest.DeletedAt = *v
			case "user_id":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner user_id: bad type %T", values[i])
				}
				if v.Valid {
					tmp := model.UIntID(v.Int64)
					dest.UserID = &tmp
				} else {
					dest.UserID = nil
				}
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "created_at":
				if v, ok := values[i].(*sql.NullTime); ok {
					condition.ReleaseNullTime(v)
				}
			case "updated_at":
				if v, ok := values[i].(*sql.NullTime); ok {
					condition.ReleaseNullTime(v)
				}
			case "deleted_at":
				if v, ok := values[i].(*gorm.DeletedAt); ok {
					condition.ReleaseDeletedAt(v)
				}
			case "user_id":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "name":
				if v, ok := values[i].(*sql.NullString); ok {
					condition.ReleaseNullString(v)
				}
			default:
				if v, ok := values[i].(*condition.NullSink); ok {
					condition.ReleaseNullSink(v)
				}
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireNullInt64()
			case "created_at":
				values[i] = condition.AcquireNullTime()
			case "updated_at":
				values[i] = condition.AcquireNullTime()
			case "deleted_at":
				values[i] = condition.AcquireDeletedAt()
			case "user_id":
				values[i] = condition.AcquireNullInt64()
			case "name":
				values[i] = condition.AcquireNullString()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}

func init() {
	condition.RegisterScanner(petScanner)
}
func init() {
	Pet.ID = condition.NewField[models.Pet, model.UIntID]("ID", "", "", petScanner)
	Pet.CreatedAt = condition.NewField[models.Pet, time.Time]("CreatedAt", "", "", petScanner)
	Pet.UpdatedAt = condition.NewField[models.Pet, time.Time]("UpdatedAt", "", "", petScanner)
	Pet.DeletedAt = condition.NewField[models.Pet, time.Time]("DeletedAt", "", "", petScanner)
	Pet.UserID = condition.NewNullableField[models.Pet, model.UIntID]("UserID", "", "", petScanner)
	Pet.Name = condition.NewStringField[models.Pet]("Name", "", "", petScanner)
}
