// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/tests/models"
	"time"
)

type petConditions struct {
	ID        condition.Field[models.Pet, model.UIntID]
	CreatedAt condition.Field[models.Pet, time.Time]
	UpdatedAt condition.Field[models.Pet, time.Time]
	DeletedAt condition.Field[models.Pet, time.Time]
	UserID    condition.NullableField[models.Pet, model.UIntID]
	Name      condition.StringField[models.Pet]
}

var Pet = petConditions{
	CreatedAt: condition.NewField[models.Pet, time.Time]("CreatedAt", "", ""),
	DeletedAt: condition.NewField[models.Pet, time.Time]("DeletedAt", "", ""),
	ID:        condition.NewField[models.Pet, model.UIntID]("ID", "", ""),
	Name:      condition.NewStringField[models.Pet]("Name", "", ""),
	UpdatedAt: condition.NewField[models.Pet, time.Time]("UpdatedAt", "", ""),
	UserID:    condition.NewNullableField[models.Pet, model.UIntID]("UserID", "", ""),
}

// Preload allows preloading the Pet when doing a query
func (petConditions petConditions) preload() condition.Condition[models.Pet] {
	return condition.NewPreloadCondition[models.Pet](petConditions.ID, petConditions.CreatedAt, petConditions.UpdatedAt, petConditions.DeletedAt, petConditions.UserID, petConditions.Name)
}
