// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/tests/models"
	gorm "gorm.io/gorm"
	"time"
)

var userScanner = &condition.Scanner[models.User]{
	AssignValues: func(dest *models.User, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = model.UIntID(v.Int64)
			case "created_at":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner created_at: bad type %T", values[i])
				}
				if v.Valid {
					dest.CreatedAt = v.Time
				}
			case "updated_at":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner updated_at: bad type %T", values[i])
				}
				if v.Valid {
					dest.UpdatedAt = v.Time
				}
			case "deleted_at":
				v, ok := values[i].(*gorm.DeletedAt)
				if !ok {
					return fmt.Errorf("cql scanner deleted_at: bad type %T", values[i])
				}
				dest.DeletedAt = *v
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			case "age":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner age: bad type %T", values[i])
				}
				if v.Valid {
					dest.Age = uint(v.Int64)
				}
			case "birthday":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner birthday: bad type %T", values[i])
				}
				if v.Valid {
					tmp := v.Time
					dest.Birthday = &tmp
				} else {
					dest.Birthday = nil
				}
			case "company_id":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner company_id: bad type %T", values[i])
				}
				if v.Valid {
					tmp := int(v.Int64)
					dest.CompanyID = &tmp
				} else {
					dest.CompanyID = nil
				}
			case "active":
				v, ok := values[i].(*sql.NullBool)
				if !ok {
					return fmt.Errorf("cql scanner active: bad type %T", values[i])
				}
				if v.Valid {
					dest.Active = v.Bool
				}
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "created_at":
				if v, ok := values[i].(*sql.NullTime); ok {
					condition.ReleaseNullTime(v)
				}
			case "updated_at":
				if v, ok := values[i].(*sql.NullTime); ok {
					condition.ReleaseNullTime(v)
				}
			case "deleted_at":
				if v, ok := values[i].(*gorm.DeletedAt); ok {
					condition.ReleaseDeletedAt(v)
				}
			case "name":
				if v, ok := values[i].(*sql.NullString); ok {
					condition.ReleaseNullString(v)
				}
			case "age":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "birthday":
				if v, ok := values[i].(*sql.NullTime); ok {
					condition.ReleaseNullTime(v)
				}
			case "company_id":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "active":
				if v, ok := values[i].(*sql.NullBool); ok {
					condition.ReleaseNullBool(v)
				}
			default:
				if v, ok := values[i].(*condition.NullSink); ok {
					condition.ReleaseNullSink(v)
				}
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireNullInt64()
			case "created_at":
				values[i] = condition.AcquireNullTime()
			case "updated_at":
				values[i] = condition.AcquireNullTime()
			case "deleted_at":
				values[i] = condition.AcquireDeletedAt()
			case "name":
				values[i] = condition.AcquireNullString()
			case "age":
				values[i] = condition.AcquireNullInt64()
			case "birthday":
				values[i] = condition.AcquireNullTime()
			case "company_id":
				values[i] = condition.AcquireNullInt64()
			case "active":
				values[i] = condition.AcquireNullBool()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}

func init() {
	condition.RegisterScanner(userScanner)
}

var userAccountJoinScanner = &condition.RelationScanner[models.User, models.Account]{
	ChildScanner: accountScanner,
	Mount: func(p *models.User, c *models.Account) {
		p.Account = *c
	},
	RelationField: "Account",
}
var userPetsHasManyLoader = &condition.HasManyLoader[models.User, models.Pet]{
	BuildQuery: func(tx *gorm.DB, parentIDs []any, nested []condition.Condition[models.Pet]) (*condition.Query[models.Pet], error) {
		typedIDs := make([]condition.ValueOfType[model.UIntID], len(parentIDs))
		for i, id := range parentIDs {
			typedIDs[i] = condition.UIntID(id.(model.UIntID))
		}
		conds := append([]condition.Condition[models.Pet]{Pet.UserID.Is().In(typedIDs...)}, nested...)
		return condition.NewQuery[models.Pet](tx, conds...), nil
	},
	ChildFK: func(c *models.Pet) any {
		if c.UserID == nil {
			return model.NilUIntID
		}
		return *c.UserID
	},
	CollectionField: "Pets",
	Mount: func(p *models.User, children []*models.Pet) {
		p.Pets = children
	},
	ParentID: func(p *models.User) any {
		return p.ID
	},
}
var userNamedPetJoinScanner = &condition.RelationScanner[models.User, models.Pet]{
	ChildScanner: petScanner,
	Mount: func(p *models.User, c *models.Pet) {
		p.NamedPet = c
	},
	RelationField: "NamedPet",
	SetNil: func(p *models.User) {
		p.NamedPet = nil
	},
}

func init() {
	User.ID = condition.NewField[models.User, model.UIntID]("ID", "", "", userScanner)
	User.CreatedAt = condition.NewField[models.User, time.Time]("CreatedAt", "", "", userScanner)
	User.UpdatedAt = condition.NewField[models.User, time.Time]("UpdatedAt", "", "", userScanner)
	User.DeletedAt = condition.NewField[models.User, time.Time]("DeletedAt", "", "", userScanner)
	User.Name = condition.NewStringField[models.User]("Name", "", "", userScanner)
	User.Age = condition.NewNumericField[models.User, uint]("Age", "", "", userScanner)
	User.Birthday = condition.NewNullableField[models.User, time.Time]("Birthday", "", "", userScanner)
	User.CompanyID = condition.NewNullableNumericField[models.User, int]("CompanyID", "", "", userScanner)
	User.Active = condition.NewBoolField[models.User]("Active", "", "", userScanner)
	User.Pets = User.Pets.WithParentScanner(userScanner)
}
