// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	orm "github.com/ditrit/badaas/orm"
	model "github.com/ditrit/badaas/orm/model"
	models "github.com/ditrit/badaas/persistence/models"
	"time"
)

type userConditions struct {
	ID        orm.Field[models.User, model.UUID]
	CreatedAt orm.Field[models.User, time.Time]
	UpdatedAt orm.Field[models.User, time.Time]
	DeletedAt orm.Field[models.User, time.Time]
	Username  orm.StringField[models.User]
	Email     orm.StringField[models.User]
	Password  orm.Field[models.User, []uint8]
}

var User = userConditions{
	CreatedAt: orm.Field[models.User, time.Time]{Name: "CreatedAt"},
	DeletedAt: orm.Field[models.User, time.Time]{Name: "DeletedAt"},
	Email:     orm.StringField[models.User]{Field: orm.Field[models.User, string]{Name: "Email"}},
	ID:        orm.Field[models.User, model.UUID]{Name: "ID"},
	Password:  orm.Field[models.User, []uint8]{Name: "Password"},
	UpdatedAt: orm.Field[models.User, time.Time]{Name: "UpdatedAt"},
	Username:  orm.StringField[models.User]{Field: orm.Field[models.User, string]{Name: "Username"}},
}

// Preload allows preloading the User when doing a query
func (userConditions userConditions) Preload() orm.Condition[models.User] {
	return orm.NewPreloadCondition[models.User](userConditions.ID, userConditions.CreatedAt, userConditions.UpdatedAt, userConditions.DeletedAt, userConditions.Username, userConditions.Email, userConditions.Password)
}
