// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
	"time"
)

type allTypesConditions struct {
	ID         condition.Field[models.AllTypes, model.UUID]
	ValInt     condition.NumericField[models.AllTypes, int]
	ValInt8    condition.NumericField[models.AllTypes, int8]
	ValInt16   condition.NumericField[models.AllTypes, int16]
	ValInt32   condition.NumericField[models.AllTypes, int32]
	ValInt64   condition.NumericField[models.AllTypes, int64]
	ValUint    condition.NumericField[models.AllTypes, uint]
	ValUint8   condition.NumericField[models.AllTypes, uint8]
	ValUint16  condition.NumericField[models.AllTypes, uint16]
	ValUint32  condition.NumericField[models.AllTypes, uint32]
	ValUint64  condition.NumericField[models.AllTypes, uint64]
	ValFloat32 condition.NumericField[models.AllTypes, float32]
	ValFloat64 condition.NumericField[models.AllTypes, float64]
	ValBool    condition.BoolField[models.AllTypes]
	ValString  condition.StringField[models.AllTypes]
	ValTime    condition.UpdatableField[models.AllTypes, time.Time]
	PtrInt     condition.NullableNumericField[models.AllTypes, int]
	PtrInt8    condition.NullableNumericField[models.AllTypes, int8]
	PtrInt16   condition.NullableNumericField[models.AllTypes, int16]
	PtrInt32   condition.NullableNumericField[models.AllTypes, int32]
	PtrInt64   condition.NullableNumericField[models.AllTypes, int64]
	PtrUint    condition.NullableNumericField[models.AllTypes, uint]
	PtrUint8   condition.NullableNumericField[models.AllTypes, uint8]
	PtrUint16  condition.NullableNumericField[models.AllTypes, uint16]
	PtrUint32  condition.NullableNumericField[models.AllTypes, uint32]
	PtrUint64  condition.NullableNumericField[models.AllTypes, uint64]
	PtrFloat32 condition.NullableNumericField[models.AllTypes, float32]
	PtrFloat64 condition.NullableNumericField[models.AllTypes, float64]
	PtrBool    condition.NullableBoolField[models.AllTypes]
	PtrString  condition.NullableStringField[models.AllTypes]
	PtrTime    condition.NullableField[models.AllTypes, time.Time]
}

var AllTypes = allTypesConditions{
	ID:         condition.NewField[models.AllTypes, model.UUID]("ID", "", ""),
	PtrBool:    condition.NewNullableBoolField[models.AllTypes]("PtrBool", "", ""),
	PtrFloat32: condition.NewNullableNumericField[models.AllTypes, float32]("PtrFloat32", "", ""),
	PtrFloat64: condition.NewNullableNumericField[models.AllTypes, float64]("PtrFloat64", "", ""),
	PtrInt:     condition.NewNullableNumericField[models.AllTypes, int]("PtrInt", "", ""),
	PtrInt16:   condition.NewNullableNumericField[models.AllTypes, int16]("PtrInt16", "", ""),
	PtrInt32:   condition.NewNullableNumericField[models.AllTypes, int32]("PtrInt32", "", ""),
	PtrInt64:   condition.NewNullableNumericField[models.AllTypes, int64]("PtrInt64", "", ""),
	PtrInt8:    condition.NewNullableNumericField[models.AllTypes, int8]("PtrInt8", "", ""),
	PtrString:  condition.NewNullableStringField[models.AllTypes]("PtrString", "", ""),
	PtrTime:    condition.NewNullableField[models.AllTypes, time.Time]("PtrTime", "", ""),
	PtrUint:    condition.NewNullableNumericField[models.AllTypes, uint]("PtrUint", "", ""),
	PtrUint16:  condition.NewNullableNumericField[models.AllTypes, uint16]("PtrUint16", "", ""),
	PtrUint32:  condition.NewNullableNumericField[models.AllTypes, uint32]("PtrUint32", "", ""),
	PtrUint64:  condition.NewNullableNumericField[models.AllTypes, uint64]("PtrUint64", "", ""),
	PtrUint8:   condition.NewNullableNumericField[models.AllTypes, uint8]("PtrUint8", "", ""),
	ValBool:    condition.NewBoolField[models.AllTypes]("ValBool", "", ""),
	ValFloat32: condition.NewNumericField[models.AllTypes, float32]("ValFloat32", "", ""),
	ValFloat64: condition.NewNumericField[models.AllTypes, float64]("ValFloat64", "", ""),
	ValInt:     condition.NewNumericField[models.AllTypes, int]("ValInt", "", ""),
	ValInt16:   condition.NewNumericField[models.AllTypes, int16]("ValInt16", "", ""),
	ValInt32:   condition.NewNumericField[models.AllTypes, int32]("ValInt32", "", ""),
	ValInt64:   condition.NewNumericField[models.AllTypes, int64]("ValInt64", "", ""),
	ValInt8:    condition.NewNumericField[models.AllTypes, int8]("ValInt8", "", ""),
	ValString:  condition.NewStringField[models.AllTypes]("ValString", "", ""),
	ValTime:    condition.NewUpdatableField[models.AllTypes, time.Time]("ValTime", "", ""),
	ValUint:    condition.NewNumericField[models.AllTypes, uint]("ValUint", "", ""),
	ValUint16:  condition.NewNumericField[models.AllTypes, uint16]("ValUint16", "", ""),
	ValUint32:  condition.NewNumericField[models.AllTypes, uint32]("ValUint32", "", ""),
	ValUint64:  condition.NewNumericField[models.AllTypes, uint64]("ValUint64", "", ""),
	ValUint8:   condition.NewNumericField[models.AllTypes, uint8]("ValUint8", "", ""),
}

// Preload allows preloading the AllTypes when doing a query
func (allTypesConditions allTypesConditions) preload() condition.Condition[models.AllTypes] {
	return condition.NewPreloadCondition[models.AllTypes](allTypesConditions.ID, allTypesConditions.ValInt, allTypesConditions.ValInt8, allTypesConditions.ValInt16, allTypesConditions.ValInt32, allTypesConditions.ValInt64, allTypesConditions.ValUint, allTypesConditions.ValUint8, allTypesConditions.ValUint16, allTypesConditions.ValUint32, allTypesConditions.ValUint64, allTypesConditions.ValFloat32, allTypesConditions.ValFloat64, allTypesConditions.ValBool, allTypesConditions.ValString, allTypesConditions.ValTime, allTypesConditions.PtrInt, allTypesConditions.PtrInt8, allTypesConditions.PtrInt16, allTypesConditions.PtrInt32, allTypesConditions.PtrInt64, allTypesConditions.PtrUint, allTypesConditions.PtrUint8, allTypesConditions.PtrUint16, allTypesConditions.PtrUint32, allTypesConditions.PtrUint64, allTypesConditions.PtrFloat32, allTypesConditions.PtrFloat64, allTypesConditions.PtrBool, allTypesConditions.PtrString, allTypesConditions.PtrTime)
}
