// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
	"time"
)

var allTypesScanner = &condition.Scanner[models.AllTypes]{
	AssignValues: func(dest *models.AllTypes, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "val_int":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner val_int: bad type %T", values[i])
				}
				if v.Valid {
					dest.ValInt = int(v.Int64)
				}
			case "val_int8":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner val_int8: bad type %T", values[i])
				}
				if v.Valid {
					dest.ValInt8 = int8(v.Int64)
				}
			case "val_int16":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner val_int16: bad type %T", values[i])
				}
				if v.Valid {
					dest.ValInt16 = int16(v.Int64)
				}
			case "val_int32":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner val_int32: bad type %T", values[i])
				}
				if v.Valid {
					dest.ValInt32 = int32(v.Int64)
				}
			case "val_int64":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner val_int64: bad type %T", values[i])
				}
				if v.Valid {
					dest.ValInt64 = int64(v.Int64)
				}
			case "val_uint":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner val_uint: bad type %T", values[i])
				}
				if v.Valid {
					dest.ValUint = uint(v.Int64)
				}
			case "val_uint8":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner val_uint8: bad type %T", values[i])
				}
				if v.Valid {
					dest.ValUint8 = uint8(v.Int64)
				}
			case "val_uint16":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner val_uint16: bad type %T", values[i])
				}
				if v.Valid {
					dest.ValUint16 = uint16(v.Int64)
				}
			case "val_uint32":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner val_uint32: bad type %T", values[i])
				}
				if v.Valid {
					dest.ValUint32 = uint32(v.Int64)
				}
			case "val_uint64":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner val_uint64: bad type %T", values[i])
				}
				if v.Valid {
					dest.ValUint64 = uint64(v.Int64)
				}
			case "val_float32":
				v, ok := values[i].(*sql.NullFloat64)
				if !ok {
					return fmt.Errorf("cql scanner val_float32: bad type %T", values[i])
				}
				if v.Valid {
					dest.ValFloat32 = float32(v.Float64)
				}
			case "val_float64":
				v, ok := values[i].(*sql.NullFloat64)
				if !ok {
					return fmt.Errorf("cql scanner val_float64: bad type %T", values[i])
				}
				if v.Valid {
					dest.ValFloat64 = v.Float64
				}
			case "val_bool":
				v, ok := values[i].(*sql.NullBool)
				if !ok {
					return fmt.Errorf("cql scanner val_bool: bad type %T", values[i])
				}
				if v.Valid {
					dest.ValBool = v.Bool
				}
			case "val_string":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner val_string: bad type %T", values[i])
				}
				if v.Valid {
					dest.ValString = v.String
				}
			case "val_time":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner val_time: bad type %T", values[i])
				}
				if v.Valid {
					dest.ValTime = v.Time
				}
			case "ptr_int":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner ptr_int: bad type %T", values[i])
				}
				if v.Valid {
					tmp := int(v.Int64)
					dest.PtrInt = &tmp
				} else {
					dest.PtrInt = nil
				}
			case "ptr_int8":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner ptr_int8: bad type %T", values[i])
				}
				if v.Valid {
					tmp := int8(v.Int64)
					dest.PtrInt8 = &tmp
				} else {
					dest.PtrInt8 = nil
				}
			case "ptr_int16":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner ptr_int16: bad type %T", values[i])
				}
				if v.Valid {
					tmp := int16(v.Int64)
					dest.PtrInt16 = &tmp
				} else {
					dest.PtrInt16 = nil
				}
			case "ptr_int32":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner ptr_int32: bad type %T", values[i])
				}
				if v.Valid {
					tmp := int32(v.Int64)
					dest.PtrInt32 = &tmp
				} else {
					dest.PtrInt32 = nil
				}
			case "ptr_int64":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner ptr_int64: bad type %T", values[i])
				}
				if v.Valid {
					tmp := int64(v.Int64)
					dest.PtrInt64 = &tmp
				} else {
					dest.PtrInt64 = nil
				}
			case "ptr_uint":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner ptr_uint: bad type %T", values[i])
				}
				if v.Valid {
					tmp := uint(v.Int64)
					dest.PtrUint = &tmp
				} else {
					dest.PtrUint = nil
				}
			case "ptr_uint8":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner ptr_uint8: bad type %T", values[i])
				}
				if v.Valid {
					tmp := uint8(v.Int64)
					dest.PtrUint8 = &tmp
				} else {
					dest.PtrUint8 = nil
				}
			case "ptr_uint16":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner ptr_uint16: bad type %T", values[i])
				}
				if v.Valid {
					tmp := uint16(v.Int64)
					dest.PtrUint16 = &tmp
				} else {
					dest.PtrUint16 = nil
				}
			case "ptr_uint32":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner ptr_uint32: bad type %T", values[i])
				}
				if v.Valid {
					tmp := uint32(v.Int64)
					dest.PtrUint32 = &tmp
				} else {
					dest.PtrUint32 = nil
				}
			case "ptr_uint64":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner ptr_uint64: bad type %T", values[i])
				}
				if v.Valid {
					tmp := uint64(v.Int64)
					dest.PtrUint64 = &tmp
				} else {
					dest.PtrUint64 = nil
				}
			case "ptr_float32":
				v, ok := values[i].(*sql.NullFloat64)
				if !ok {
					return fmt.Errorf("cql scanner ptr_float32: bad type %T", values[i])
				}
				if v.Valid {
					tmp := float32(v.Float64)
					dest.PtrFloat32 = &tmp
				} else {
					dest.PtrFloat32 = nil
				}
			case "ptr_float64":
				v, ok := values[i].(*sql.NullFloat64)
				if !ok {
					return fmt.Errorf("cql scanner ptr_float64: bad type %T", values[i])
				}
				if v.Valid {
					tmp := float64(v.Float64)
					dest.PtrFloat64 = &tmp
				} else {
					dest.PtrFloat64 = nil
				}
			case "ptr_bool":
				v, ok := values[i].(*sql.NullBool)
				if !ok {
					return fmt.Errorf("cql scanner ptr_bool: bad type %T", values[i])
				}
				if v.Valid {
					tmp := bool(v.Bool)
					dest.PtrBool = &tmp
				} else {
					dest.PtrBool = nil
				}
			case "ptr_string":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner ptr_string: bad type %T", values[i])
				}
				if v.Valid {
					tmp := string(v.String)
					dest.PtrString = &tmp
				} else {
					dest.PtrString = nil
				}
			case "ptr_time":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner ptr_time: bad type %T", values[i])
				}
				if v.Valid {
					tmp := v.Time
					dest.PtrTime = &tmp
				} else {
					dest.PtrTime = nil
				}
			case "null_int16":
				v, ok := values[i].(*sql.NullInt16)
				if !ok {
					return fmt.Errorf("cql scanner null_int16: bad type %T", values[i])
				}
				dest.NullInt16 = *v
			case "null_int32":
				v, ok := values[i].(*sql.NullInt32)
				if !ok {
					return fmt.Errorf("cql scanner null_int32: bad type %T", values[i])
				}
				dest.NullInt32 = *v
			case "null_byte":
				v, ok := values[i].(*sql.NullByte)
				if !ok {
					return fmt.Errorf("cql scanner null_byte: bad type %T", values[i])
				}
				dest.NullByte = *v
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				if v, ok := values[i].(*model.UUID); ok {
					condition.ReleaseUUID(v)
				}
			case "val_int":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "val_int8":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "val_int16":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "val_int32":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "val_int64":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "val_uint":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "val_uint8":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "val_uint16":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "val_uint32":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "val_uint64":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "val_float32":
				if v, ok := values[i].(*sql.NullFloat64); ok {
					condition.ReleaseNullFloat64(v)
				}
			case "val_float64":
				if v, ok := values[i].(*sql.NullFloat64); ok {
					condition.ReleaseNullFloat64(v)
				}
			case "val_bool":
				if v, ok := values[i].(*sql.NullBool); ok {
					condition.ReleaseNullBool(v)
				}
			case "val_string":
				if v, ok := values[i].(*sql.NullString); ok {
					condition.ReleaseNullString(v)
				}
			case "val_time":
				if v, ok := values[i].(*sql.NullTime); ok {
					condition.ReleaseNullTime(v)
				}
			case "ptr_int":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "ptr_int8":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "ptr_int16":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "ptr_int32":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "ptr_int64":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "ptr_uint":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "ptr_uint8":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "ptr_uint16":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "ptr_uint32":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "ptr_uint64":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "ptr_float32":
				if v, ok := values[i].(*sql.NullFloat64); ok {
					condition.ReleaseNullFloat64(v)
				}
			case "ptr_float64":
				if v, ok := values[i].(*sql.NullFloat64); ok {
					condition.ReleaseNullFloat64(v)
				}
			case "ptr_bool":
				if v, ok := values[i].(*sql.NullBool); ok {
					condition.ReleaseNullBool(v)
				}
			case "ptr_string":
				if v, ok := values[i].(*sql.NullString); ok {
					condition.ReleaseNullString(v)
				}
			case "ptr_time":
				if v, ok := values[i].(*sql.NullTime); ok {
					condition.ReleaseNullTime(v)
				}
			case "null_int16":
				if v, ok := values[i].(*sql.NullInt16); ok {
					condition.ReleaseNullInt16(v)
				}
			case "null_int32":
				if v, ok := values[i].(*sql.NullInt32); ok {
					condition.ReleaseNullInt32(v)
				}
			case "null_byte":
				if v, ok := values[i].(*sql.NullByte); ok {
					condition.ReleaseNullByte(v)
				}
			default:
				if v, ok := values[i].(*condition.NullSink); ok {
					condition.ReleaseNullSink(v)
				}
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireUUID()
			case "val_int":
				values[i] = condition.AcquireNullInt64()
			case "val_int8":
				values[i] = condition.AcquireNullInt64()
			case "val_int16":
				values[i] = condition.AcquireNullInt64()
			case "val_int32":
				values[i] = condition.AcquireNullInt64()
			case "val_int64":
				values[i] = condition.AcquireNullInt64()
			case "val_uint":
				values[i] = condition.AcquireNullInt64()
			case "val_uint8":
				values[i] = condition.AcquireNullInt64()
			case "val_uint16":
				values[i] = condition.AcquireNullInt64()
			case "val_uint32":
				values[i] = condition.AcquireNullInt64()
			case "val_uint64":
				values[i] = condition.AcquireNullInt64()
			case "val_float32":
				values[i] = condition.AcquireNullFloat64()
			case "val_float64":
				values[i] = condition.AcquireNullFloat64()
			case "val_bool":
				values[i] = condition.AcquireNullBool()
			case "val_string":
				values[i] = condition.AcquireNullString()
			case "val_time":
				values[i] = condition.AcquireNullTime()
			case "ptr_int":
				values[i] = condition.AcquireNullInt64()
			case "ptr_int8":
				values[i] = condition.AcquireNullInt64()
			case "ptr_int16":
				values[i] = condition.AcquireNullInt64()
			case "ptr_int32":
				values[i] = condition.AcquireNullInt64()
			case "ptr_int64":
				values[i] = condition.AcquireNullInt64()
			case "ptr_uint":
				values[i] = condition.AcquireNullInt64()
			case "ptr_uint8":
				values[i] = condition.AcquireNullInt64()
			case "ptr_uint16":
				values[i] = condition.AcquireNullInt64()
			case "ptr_uint32":
				values[i] = condition.AcquireNullInt64()
			case "ptr_uint64":
				values[i] = condition.AcquireNullInt64()
			case "ptr_float32":
				values[i] = condition.AcquireNullFloat64()
			case "ptr_float64":
				values[i] = condition.AcquireNullFloat64()
			case "ptr_bool":
				values[i] = condition.AcquireNullBool()
			case "ptr_string":
				values[i] = condition.AcquireNullString()
			case "ptr_time":
				values[i] = condition.AcquireNullTime()
			case "null_int16":
				values[i] = condition.AcquireNullInt16()
			case "null_int32":
				values[i] = condition.AcquireNullInt32()
			case "null_byte":
				values[i] = condition.AcquireNullByte()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}

func init() {
	condition.RegisterScanner(allTypesScanner)
	AllTypes.ID = condition.NewField[models.AllTypes, model.UUID]("ID", "", "", allTypesScanner)
	AllTypes.ValInt = condition.NewNumericField[models.AllTypes, int]("ValInt", "", "", allTypesScanner)
	AllTypes.ValInt8 = condition.NewNumericField[models.AllTypes, int8]("ValInt8", "", "", allTypesScanner)
	AllTypes.ValInt16 = condition.NewNumericField[models.AllTypes, int16]("ValInt16", "", "", allTypesScanner)
	AllTypes.ValInt32 = condition.NewNumericField[models.AllTypes, int32]("ValInt32", "", "", allTypesScanner)
	AllTypes.ValInt64 = condition.NewNumericField[models.AllTypes, int64]("ValInt64", "", "", allTypesScanner)
	AllTypes.ValUint = condition.NewNumericField[models.AllTypes, uint]("ValUint", "", "", allTypesScanner)
	AllTypes.ValUint8 = condition.NewNumericField[models.AllTypes, uint8]("ValUint8", "", "", allTypesScanner)
	AllTypes.ValUint16 = condition.NewNumericField[models.AllTypes, uint16]("ValUint16", "", "", allTypesScanner)
	AllTypes.ValUint32 = condition.NewNumericField[models.AllTypes, uint32]("ValUint32", "", "", allTypesScanner)
	AllTypes.ValUint64 = condition.NewNumericField[models.AllTypes, uint64]("ValUint64", "", "", allTypesScanner)
	AllTypes.ValFloat32 = condition.NewNumericField[models.AllTypes, float32]("ValFloat32", "", "", allTypesScanner)
	AllTypes.ValFloat64 = condition.NewNumericField[models.AllTypes, float64]("ValFloat64", "", "", allTypesScanner)
	AllTypes.ValBool = condition.NewBoolField[models.AllTypes]("ValBool", "", "", allTypesScanner)
	AllTypes.ValString = condition.NewStringField[models.AllTypes]("ValString", "", "", allTypesScanner)
	AllTypes.ValTime = condition.NewUpdatableField[models.AllTypes, time.Time]("ValTime", "", "", allTypesScanner)
	AllTypes.PtrInt = condition.NewNullableNumericField[models.AllTypes, int]("PtrInt", "", "", allTypesScanner)
	AllTypes.PtrInt8 = condition.NewNullableNumericField[models.AllTypes, int8]("PtrInt8", "", "", allTypesScanner)
	AllTypes.PtrInt16 = condition.NewNullableNumericField[models.AllTypes, int16]("PtrInt16", "", "", allTypesScanner)
	AllTypes.PtrInt32 = condition.NewNullableNumericField[models.AllTypes, int32]("PtrInt32", "", "", allTypesScanner)
	AllTypes.PtrInt64 = condition.NewNullableNumericField[models.AllTypes, int64]("PtrInt64", "", "", allTypesScanner)
	AllTypes.PtrUint = condition.NewNullableNumericField[models.AllTypes, uint]("PtrUint", "", "", allTypesScanner)
	AllTypes.PtrUint8 = condition.NewNullableNumericField[models.AllTypes, uint8]("PtrUint8", "", "", allTypesScanner)
	AllTypes.PtrUint16 = condition.NewNullableNumericField[models.AllTypes, uint16]("PtrUint16", "", "", allTypesScanner)
	AllTypes.PtrUint32 = condition.NewNullableNumericField[models.AllTypes, uint32]("PtrUint32", "", "", allTypesScanner)
	AllTypes.PtrUint64 = condition.NewNullableNumericField[models.AllTypes, uint64]("PtrUint64", "", "", allTypesScanner)
	AllTypes.PtrFloat32 = condition.NewNullableNumericField[models.AllTypes, float32]("PtrFloat32", "", "", allTypesScanner)
	AllTypes.PtrFloat64 = condition.NewNullableNumericField[models.AllTypes, float64]("PtrFloat64", "", "", allTypesScanner)
	AllTypes.PtrBool = condition.NewNullableBoolField[models.AllTypes]("PtrBool", "", "", allTypesScanner)
	AllTypes.PtrString = condition.NewNullableStringField[models.AllTypes]("PtrString", "", "", allTypesScanner)
	AllTypes.PtrTime = condition.NewNullableField[models.AllTypes, time.Time]("PtrTime", "", "", allTypesScanner)
	AllTypes.NullInt16 = condition.NewNullableNumericField[models.AllTypes, int16]("NullInt16", "", "", allTypesScanner)
	AllTypes.NullInt32 = condition.NewNullableNumericField[models.AllTypes, int32]("NullInt32", "", "", allTypesScanner)
	AllTypes.NullByte = condition.NewNullableNumericField[models.AllTypes, int8]("NullByte", "", "", allTypesScanner)
}
