// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
	decimal "github.com/shopspring/decimal"
)

type bankConditions struct {
	ID      condition.Field[models.Bank, model.UUID]
	Balance condition.DecimalField[models.Bank, models.Cents]
	Rate    condition.DecimalField[models.Bank, decimal.Decimal]
}

var Bank = bankConditions{
	Balance: condition.NewDecimalField[models.Bank, models.Cents]("Balance", "", ""),
	ID:      condition.NewField[models.Bank, model.UUID]("ID", "", ""),
	Rate:    condition.NewDecimalField[models.Bank, decimal.Decimal]("Rate", "", ""),
}

// Preload allows preloading the Bank when doing a query
func (bankConditions bankConditions) preload() condition.Condition[models.Bank] {
	return condition.NewPreloadCondition[models.Bank](bankConditions.ID, bankConditions.Balance, bankConditions.Rate)
}
