// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
	decimal "github.com/shopspring/decimal"
)

var bankScanner = &condition.Scanner[models.Bank]{
	AssignValues: func(dest *models.Bank, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "balance":
				w, ok := values[i].(*condition.NullableScanner)
				if !ok {
					return fmt.Errorf("cql scanner balance: bad wrapper type %T", values[i])
				}
				v, ok2 := w.Inner.(*models.Cents)
				if !ok2 {
					return fmt.Errorf("cql scanner balance: bad inner type %T", w.Inner)
				}
				dest.Balance = *v
			case "rate":
				w, ok := values[i].(*condition.NullableScanner)
				if !ok {
					return fmt.Errorf("cql scanner rate: bad wrapper type %T", values[i])
				}
				v, ok2 := w.Inner.(*decimal.Decimal)
				if !ok2 {
					return fmt.Errorf("cql scanner rate: bad inner type %T", w.Inner)
				}
				dest.Rate = *v
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				condition.ReleaseUUID(values[i])
			default:
				condition.ReleaseNullSink(values[i])
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireUUID()
			case "balance":
				values[i] = &condition.NullableScanner{Inner: new(models.Cents)}
			case "rate":
				values[i] = &condition.NullableScanner{Inner: new(decimal.Decimal)}
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}

func init() {
	condition.RegisterScanner(bankScanner)
	Bank.ID = condition.NewField[models.Bank, model.UUID]("ID", "", "", bankScanner)
	Bank.Balance = condition.NewDecimalField[models.Bank, models.Cents]("Balance", "", "", bankScanner)
	Bank.Rate = condition.NewDecimalField[models.Bank, decimal.Decimal]("Rate", "", "", bankScanner)
}
