// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

var bicycleScanner = &condition.Scanner[models.Bicycle]{
	AssignValues: func(dest *models.Bicycle, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			case "owner_name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner owner_name: bad type %T", values[i])
				}
				if v.Valid {
					dest.OwnerName = v.String
				}
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				if v, ok := values[i].(*model.UUID); ok {
					condition.ReleaseUUID(v)
				}
			case "name":
				if v, ok := values[i].(*sql.NullString); ok {
					condition.ReleaseNullString(v)
				}
			case "owner_name":
				if v, ok := values[i].(*sql.NullString); ok {
					condition.ReleaseNullString(v)
				}
			default:
				if v, ok := values[i].(*condition.NullSink); ok {
					condition.ReleaseNullSink(v)
				}
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireUUID()
			case "name":
				values[i] = condition.AcquireNullString()
			case "owner_name":
				values[i] = condition.AcquireNullString()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}
var bicycleOwnerJoinScanner = &condition.RelationScanner[models.Bicycle, models.Person]{
	ChildScanner: personScanner,
	Mount: func(p *models.Bicycle, c *models.Person) {
		p.Owner = *c
	},
	RelationField: "Owner",
}

func init() {
	Bicycle.ID = condition.NewField[models.Bicycle, model.UUID]("ID", "", "", bicycleScanner)
	Bicycle.Name = condition.NewStringField[models.Bicycle]("Name", "", "", bicycleScanner)
	Bicycle.OwnerName = condition.NewStringField[models.Bicycle]("OwnerName", "", "", bicycleScanner)
}
