// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

var brandScanner = &condition.Scanner[models.Brand]{
	AssignValues: func(dest *models.Brand, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = model.UIntID(v.Int64)
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "name":
				if v, ok := values[i].(*sql.NullString); ok {
					condition.ReleaseNullString(v)
				}
			default:
				if v, ok := values[i].(*condition.NullSink); ok {
					condition.ReleaseNullSink(v)
				}
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireNullInt64()
			case "name":
				values[i] = condition.AcquireNullString()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}

func init() {
	Brand.ID = condition.NewField[models.Brand, model.UIntID]("ID", "", "", brandScanner)
	Brand.Name = condition.NewStringField[models.Brand]("Name", "", "", brandScanner)
}
