// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

var childScanner = &condition.Scanner[models.Child]{
	AssignValues: func(dest *models.Child, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			case "number":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner number: bad type %T", values[i])
				}
				if v.Valid {
					dest.Number = int(v.Int64)
				}
			case "parent1_id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner parent1_id: bad type %T", values[i])
				}
				dest.Parent1ID = *v
			case "parent2_id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner parent2_id: bad type %T", values[i])
				}
				dest.Parent2ID = *v
			}
		}
		return nil
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = new(model.UUID)
			case "name":
				values[i] = new(sql.NullString)
			case "number":
				values[i] = new(sql.NullInt64)
			case "parent1_id":
				values[i] = new(model.UUID)
			case "parent2_id":
				values[i] = new(model.UUID)
			default:
				values[i] = new(condition.NullSink)
			}
		}
		return values, nil
	},
}
var childParent1JoinScanner = &condition.RelationScanner[models.Child, models.Parent1]{
	ChildScanner: parent1Scanner,
	Mount: func(p *models.Child, c *models.Parent1) {
		p.Parent1 = *c
	},
	RelationField: "Parent1",
}
var childParent2JoinScanner = &condition.RelationScanner[models.Child, models.Parent2]{
	ChildScanner: parent2Scanner,
	Mount: func(p *models.Child, c *models.Parent2) {
		p.Parent2 = *c
	},
	RelationField: "Parent2",
}

func init() {
	Child.ID = condition.NewField[models.Child, model.UUID]("ID", "", "", childScanner)
	Child.Name = condition.NewStringField[models.Child]("Name", "", "", childScanner)
	Child.Number = condition.NewNumericField[models.Child, int]("Number", "", "", childScanner)
	Child.Parent1ID = condition.NewUpdatableField[models.Child, model.UUID]("Parent1ID", "", "", childScanner)
	Child.Parent2ID = condition.NewUpdatableField[models.Child, model.UUID]("Parent2ID", "", "", childScanner)
}
