// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

var cityScanner = &condition.Scanner[models.City]{
	AssignValues: func(dest *models.City, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			case "country_id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner country_id: bad type %T", values[i])
				}
				dest.CountryID = *v
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				if v, ok := values[i].(*model.UUID); ok {
					condition.ReleaseUUID(v)
				}
			case "name":
				if v, ok := values[i].(*sql.NullString); ok {
					condition.ReleaseNullString(v)
				}
			case "country_id":
				if v, ok := values[i].(*model.UUID); ok {
					condition.ReleaseUUID(v)
				}
			default:
				if v, ok := values[i].(*condition.NullSink); ok {
					condition.ReleaseNullSink(v)
				}
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireUUID()
			case "name":
				values[i] = condition.AcquireNullString()
			case "country_id":
				values[i] = condition.AcquireUUID()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}
var cityCountryJoinScanner = &condition.RelationScanner[models.City, models.Country]{
	ChildScanner: countryScanner,
	Mount: func(p *models.City, c *models.Country) {
		p.Country = c
	},
	RelationField: "Country",
	SetNil: func(p *models.City) {
		p.Country = nil
	},
}

func init() {
	condition.RegisterScanner(cityScanner)
	City.ID = condition.NewField[models.City, model.UUID]("ID", "", "", cityScanner)
	City.Name = condition.NewStringField[models.City]("Name", "", "", cityScanner)
	City.CountryID = condition.NewUpdatableField[models.City, model.UUID]("CountryID", "", "", cityScanner)
}
