// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

type companyNoTimestampsConditions struct {
	ID      condition.Field[models.CompanyNoTimestamps, model.UUID]
	Name    condition.StringField[models.CompanyNoTimestamps]
	Sellers condition.Collection[models.CompanyNoTimestamps, models.SellerNoTimestamps]
}

var CompanyNoTimestamps = companyNoTimestampsConditions{
	ID:      condition.NewField[models.CompanyNoTimestamps, model.UUID]("ID", "", ""),
	Name:    condition.NewStringField[models.CompanyNoTimestamps]("Name", "", ""),
	Sellers: condition.NewCollection[models.CompanyNoTimestamps, models.SellerNoTimestamps]("Sellers", "ID", "CompanyNoTimestampsID"),
}

// Preload allows preloading the CompanyNoTimestamps when doing a query
func (companyNoTimestampsConditions companyNoTimestampsConditions) preload() condition.Condition[models.CompanyNoTimestamps] {
	return condition.NewPreloadCondition[models.CompanyNoTimestamps](companyNoTimestampsConditions.ID, companyNoTimestampsConditions.Name)
}
