// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
	gorm "gorm.io/gorm"
	"time"
)

var companyScanner = &condition.Scanner[models.Company]{
	AssignValues: func(dest *models.Company, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "created_at":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner created_at: bad type %T", values[i])
				}
				if v.Valid {
					dest.CreatedAt = v.Time
				}
			case "updated_at":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner updated_at: bad type %T", values[i])
				}
				if v.Valid {
					dest.UpdatedAt = v.Time
				}
			case "deleted_at":
				v, ok := values[i].(*gorm.DeletedAt)
				if !ok {
					return fmt.Errorf("cql scanner deleted_at: bad type %T", values[i])
				}
				dest.DeletedAt = *v
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			}
		}
		return nil
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = new(model.UUID)
			case "created_at":
				values[i] = new(sql.NullTime)
			case "updated_at":
				values[i] = new(sql.NullTime)
			case "deleted_at":
				values[i] = new(gorm.DeletedAt)
			case "name":
				values[i] = new(sql.NullString)
			default:
				values[i] = new(condition.NullSink)
			}
		}
		return values, nil
	},
}
var companySellersHasManyLoader = &condition.HasManyLoader[models.Company, models.Seller]{
	BuildQuery: func(tx *gorm.DB, parentIDs []any, nested []condition.Condition[models.Seller]) (*condition.Query[models.Seller], error) {
		typedIDs := make([]condition.ValueOfType[model.UUID], len(parentIDs))
		for i, id := range parentIDs {
			typedIDs[i] = condition.UUID(id.(model.UUID))
		}
		conds := append([]condition.Condition[models.Seller]{Seller.CompanyID.Is().In(typedIDs...)}, nested...)
		return condition.NewQuery[models.Seller](tx, conds...), nil
	},
	ChildFK: func(c *models.Seller) any {
		if c.CompanyID == nil {
			return model.NilUUID
		}
		return *c.CompanyID
	},
	CollectionField: "Sellers",
	Mount: func(p *models.Company, children []*models.Seller) {
		values := make([]models.Seller, len(children))
		for i, c := range children {
			values[i] = *c
		}
		p.Sellers = &values
	},
	ParentID: func(p *models.Company) any {
		return p.ID
	},
}

func init() {
	Company.ID = condition.NewField[models.Company, model.UUID]("ID", "", "", companyScanner)
	Company.CreatedAt = condition.NewField[models.Company, time.Time]("CreatedAt", "", "", companyScanner)
	Company.UpdatedAt = condition.NewField[models.Company, time.Time]("UpdatedAt", "", "", companyScanner)
	Company.DeletedAt = condition.NewField[models.Company, time.Time]("DeletedAt", "", "", companyScanner)
	Company.Name = condition.NewStringField[models.Company]("Name", "", "", companyScanner)
	Company.Sellers = Company.Sellers.WithParentScanner(companyScanner)
}
