// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

var companyNoTimestampsScanner = &condition.Scanner[models.CompanyNoTimestamps]{
	AssignValues: func(dest *models.CompanyNoTimestamps, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			}
		}
		return nil
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = new(model.UUID)
			case "name":
				values[i] = new(sql.NullString)
			default:
				values[i] = new(condition.NullSink)
			}
		}
		return values, nil
	},
}

func init() {
	CompanyNoTimestamps.ID = condition.NewField[models.CompanyNoTimestamps, model.UUID]("ID", "", "", companyNoTimestampsScanner)
	CompanyNoTimestamps.Name = condition.NewStringField[models.CompanyNoTimestamps]("Name", "", "", companyNoTimestampsScanner)
}
