// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

func (countryConditions countryConditions) Capital(conditions ...condition.Condition[models.City]) condition.JoinCondition[models.Country] {
	return condition.NewJoinCondition[models.Country, models.City](conditions, "Capital", "ID", countryConditions.preload(), "CountryID", City.preload())
}

type countryConditions struct {
	ID   condition.Field[models.Country, model.UUID]
	Name condition.StringField[models.Country]
}

var Country = countryConditions{
	ID:   condition.NewField[models.Country, model.UUID]("ID", "", ""),
	Name: condition.NewStringField[models.Country]("Name", "", ""),
}

// Preload allows preloading the Country when doing a query
func (countryConditions countryConditions) preload() condition.Condition[models.Country] {
	return condition.NewPreloadCondition[models.Country](countryConditions.ID, countryConditions.Name)
}
