// Code generated by cql-gen v0.0.5, DO NOT EDIT.
package conditions

import (
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
	"time"
)

func (countryConditions countryConditions) Capital(conditions ...condition.Condition[models.City]) condition.JoinCondition[models.Country] {
	return condition.NewJoinCondition[models.Country, models.City](conditions, "Capital", "ID", countryConditions.preload(), "CountryID", City.preload())
}

type countryConditions struct {
	ID        condition.Field[models.Country, model.UUID]
	CreatedAt condition.Field[models.Country, time.Time]
	UpdatedAt condition.Field[models.Country, time.Time]
	DeletedAt condition.Field[models.Country, time.Time]
	Name      condition.StringField[models.Country]
}

var Country = countryConditions{
	CreatedAt: condition.Field[models.Country, time.Time]{Name: "CreatedAt"},
	DeletedAt: condition.Field[models.Country, time.Time]{Name: "DeletedAt"},
	ID:        condition.Field[models.Country, model.UUID]{Name: "ID"},
	Name:      condition.StringField[models.Country]{UpdatableField: condition.UpdatableField[models.Country, string]{Field: condition.Field[models.Country, string]{Name: "Name"}}},
	UpdatedAt: condition.Field[models.Country, time.Time]{Name: "UpdatedAt"},
}

// Preload allows preloading the Country when doing a query
func (countryConditions countryConditions) preload() condition.Condition[models.Country] {
	return condition.NewPreloadCondition[models.Country](countryConditions.ID, countryConditions.CreatedAt, countryConditions.UpdatedAt, countryConditions.DeletedAt, countryConditions.Name)
}
