// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

var employeeScanner = &condition.Scanner[models.Employee]{
	AssignValues: func(dest *models.Employee, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			case "boss_id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner boss_id: bad type %T", values[i])
				}
				if *v == model.NilUUID {
					dest.BossID = nil
				} else {
					tmp := *v
					dest.BossID = &tmp
				}
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				condition.ReleaseUUID(values[i])
			case "name":
				condition.ReleaseNullString(values[i])
			case "boss_id":
				condition.ReleaseUUID(values[i])
			default:
				condition.ReleaseNullSink(values[i])
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireUUID()
			case "name":
				values[i] = condition.AcquireNullString()
			case "boss_id":
				values[i] = condition.AcquireUUID()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}
var employeeBossJoinScanner = &condition.RelationScanner[models.Employee, models.Employee]{
	ChildScanner: employeeScanner,
	Mount: func(p *models.Employee, c *models.Employee) {
		p.Boss = c
	},
	RelationField: "Boss",
	SetNil: func(p *models.Employee) {
		p.Boss = nil
	},
}

func init() {
	condition.RegisterScanner(employeeScanner)
	Employee.ID = condition.NewField[models.Employee, model.UUID]("ID", "", "", employeeScanner)
	Employee.Name = condition.NewStringField[models.Employee]("Name", "", "", employeeScanner)
	Employee.BossID = condition.NewNullableField[models.Employee, model.UUID]("BossID", "", "", employeeScanner)
}
