// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

var parent2Scanner = &condition.Scanner[models.Parent2]{
	AssignValues: func(dest *models.Parent2, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "parent_parent_id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner parent_parent_id: bad type %T", values[i])
				}
				dest.ParentParentID = *v
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				if v, ok := values[i].(*model.UUID); ok {
					condition.ReleaseUUID(v)
				}
			case "parent_parent_id":
				if v, ok := values[i].(*model.UUID); ok {
					condition.ReleaseUUID(v)
				}
			default:
				if v, ok := values[i].(*condition.NullSink); ok {
					condition.ReleaseNullSink(v)
				}
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireUUID()
			case "parent_parent_id":
				values[i] = condition.AcquireUUID()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}
var parent2ParentParentJoinScanner = &condition.RelationScanner[models.Parent2, models.ParentParent]{
	ChildScanner: parentParentScanner,
	Mount: func(p *models.Parent2, c *models.ParentParent) {
		p.ParentParent = *c
	},
	RelationField: "ParentParent",
}

func init() {
	Parent2.ID = condition.NewField[models.Parent2, model.UUID]("ID", "", "", parent2Scanner)
	Parent2.ParentParentID = condition.NewUpdatableField[models.Parent2, model.UUID]("ParentParentID", "", "", parent2Scanner)
}
