// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	cql "github.com/FrancoLiberali/cql/orm/cql"
	model "github.com/FrancoLiberali/cql/orm/model"
	models "github.com/FrancoLiberali/cql/test/models"
	"time"
)

func (parent2Conditions parent2Conditions) ParentParent(conditions ...cql.Condition[models.ParentParent]) cql.JoinCondition[models.Parent2] {
	return cql.NewJoinCondition[models.Parent2, models.ParentParent](conditions, "ParentParent", "ParentParentID", parent2Conditions.Preload(), "ID")
}
func (parent2Conditions parent2Conditions) PreloadParentParent() cql.JoinCondition[models.Parent2] {
	return parent2Conditions.ParentParent(ParentParent.Preload())
}

type parent2Conditions struct {
	ID             cql.Field[models.Parent2, model.UUID]
	CreatedAt      cql.Field[models.Parent2, time.Time]
	UpdatedAt      cql.Field[models.Parent2, time.Time]
	DeletedAt      cql.Field[models.Parent2, time.Time]
	ParentParentID cql.Field[models.Parent2, model.UUID]
}

var Parent2 = parent2Conditions{
	CreatedAt:      cql.Field[models.Parent2, time.Time]{Name: "CreatedAt"},
	DeletedAt:      cql.Field[models.Parent2, time.Time]{Name: "DeletedAt"},
	ID:             cql.Field[models.Parent2, model.UUID]{Name: "ID"},
	ParentParentID: cql.Field[models.Parent2, model.UUID]{Name: "ParentParentID"},
	UpdatedAt:      cql.Field[models.Parent2, time.Time]{Name: "UpdatedAt"},
}

// Preload allows preloading the Parent2 when doing a query
func (parent2Conditions parent2Conditions) Preload() cql.Condition[models.Parent2] {
	return cql.NewPreloadCondition[models.Parent2](parent2Conditions.ID, parent2Conditions.CreatedAt, parent2Conditions.UpdatedAt, parent2Conditions.DeletedAt, parent2Conditions.ParentParentID)
}

// PreloadRelations allows preloading all the Parent2's relation when doing a query
func (parent2Conditions parent2Conditions) PreloadRelations() []cql.Condition[models.Parent2] {
	return []cql.Condition[models.Parent2]{parent2Conditions.PreloadParentParent()}
}
