// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

var parent1Scanner = &condition.Scanner[models.Parent1]{
	AssignValues: func(dest *models.Parent1, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			case "parent_parent_id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner parent_parent_id: bad type %T", values[i])
				}
				dest.ParentParentID = *v
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				if v, ok := values[i].(*model.UUID); ok {
					condition.ReleaseUUID(v)
				}
			case "name":
				if v, ok := values[i].(*sql.NullString); ok {
					condition.ReleaseNullString(v)
				}
			case "parent_parent_id":
				if v, ok := values[i].(*model.UUID); ok {
					condition.ReleaseUUID(v)
				}
			default:
				if v, ok := values[i].(*condition.NullSink); ok {
					condition.ReleaseNullSink(v)
				}
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireUUID()
			case "name":
				values[i] = condition.AcquireNullString()
			case "parent_parent_id":
				values[i] = condition.AcquireUUID()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}
var parent1ParentParentJoinScanner = &condition.RelationScanner[models.Parent1, models.ParentParent]{
	ChildScanner: parentParentScanner,
	Mount: func(p *models.Parent1, c *models.ParentParent) {
		p.ParentParent = *c
	},
	RelationField: "ParentParent",
}

func init() {
	condition.RegisterScanner(parent1Scanner)
	Parent1.ID = condition.NewField[models.Parent1, model.UUID]("ID", "", "", parent1Scanner)
	Parent1.Name = condition.NewStringField[models.Parent1]("Name", "", "", parent1Scanner)
	Parent1.ParentParentID = condition.NewUpdatableField[models.Parent1, model.UUID]("ParentParentID", "", "", parent1Scanner)
}
