// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

func (parent1Conditions parent1Conditions) ParentParent(conditions ...condition.Condition[models.ParentParent]) condition.JoinCondition[models.Parent1] {
	return condition.NewJoinCondition[models.Parent1, models.ParentParent](conditions, "ParentParent", "ParentParentID", parent1Conditions.preload(), "ID", ParentParent.preload())
}

type parent1Conditions struct {
	ID             condition.Field[models.Parent1, model.UUID]
	Name           condition.StringField[models.Parent1]
	ParentParentID condition.UpdatableField[models.Parent1, model.UUID]
}

var Parent1 = parent1Conditions{
	ID:             condition.NewField[models.Parent1, model.UUID]("ID", "", ""),
	Name:           condition.NewStringField[models.Parent1]("Name", "", ""),
	ParentParentID: condition.NewUpdatableField[models.Parent1, model.UUID]("ParentParentID", "", ""),
}

// Preload allows preloading the Parent1 when doing a query
func (parent1Conditions parent1Conditions) preload() condition.Condition[models.Parent1] {
	return condition.NewPreloadCondition[models.Parent1](parent1Conditions.ID, parent1Conditions.Name, parent1Conditions.ParentParentID)
}
