// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	cql "github.com/ditrit/badaas/orm/cql"
	model "github.com/ditrit/badaas/orm/model"
	models "github.com/ditrit/badaas/test/models"
	"time"
)

type parentParentConditions struct {
	ID        cql.Field[models.ParentParent, model.UUID]
	CreatedAt cql.Field[models.ParentParent, time.Time]
	UpdatedAt cql.Field[models.ParentParent, time.Time]
	DeletedAt cql.Field[models.ParentParent, time.Time]
	Name      cql.StringField[models.ParentParent]
	Number    cql.Field[models.ParentParent, int]
}

var ParentParent = parentParentConditions{
	CreatedAt: cql.Field[models.ParentParent, time.Time]{Name: "CreatedAt"},
	DeletedAt: cql.Field[models.ParentParent, time.Time]{Name: "DeletedAt"},
	ID:        cql.Field[models.ParentParent, model.UUID]{Name: "ID"},
	Name:      cql.StringField[models.ParentParent]{Field: cql.Field[models.ParentParent, string]{Name: "Name"}},
	Number:    cql.Field[models.ParentParent, int]{Name: "Number"},
	UpdatedAt: cql.Field[models.ParentParent, time.Time]{Name: "UpdatedAt"},
}

// Preload allows preloading the ParentParent when doing a query
func (parentParentConditions parentParentConditions) Preload() cql.Condition[models.ParentParent] {
	return cql.NewPreloadCondition[models.ParentParent](parentParentConditions.ID, parentParentConditions.CreatedAt, parentParentConditions.UpdatedAt, parentParentConditions.DeletedAt, parentParentConditions.Name, parentParentConditions.Number)
}
