// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

type parentParentConditions struct {
	ID     condition.Field[models.ParentParent, model.UUID]
	Name   condition.StringField[models.ParentParent]
	Number condition.NumericField[models.ParentParent, int]
}

var ParentParent = parentParentConditions{
	ID:     condition.NewField[models.ParentParent, model.UUID]("ID", "", ""),
	Name:   condition.NewStringField[models.ParentParent]("Name", "", ""),
	Number: condition.NewNumericField[models.ParentParent, int]("Number", "", ""),
}

// Preload allows preloading the ParentParent when doing a query
func (parentParentConditions parentParentConditions) preload() condition.Condition[models.ParentParent] {
	return condition.NewPreloadCondition[models.ParentParent](parentParentConditions.ID, parentParentConditions.Name, parentParentConditions.Number)
}
