// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

var parentParentScanner = &condition.Scanner[models.ParentParent]{
	AssignValues: func(dest *models.ParentParent, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			case "number":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner number: bad type %T", values[i])
				}
				if v.Valid {
					dest.Number = int(v.Int64)
				}
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				condition.ReleaseUUID(values[i])
			case "name":
				condition.ReleaseNullString(values[i])
			case "number":
				condition.ReleaseNullInt64(values[i])
			default:
				condition.ReleaseNullSink(values[i])
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireUUID()
			case "name":
				values[i] = condition.AcquireNullString()
			case "number":
				values[i] = condition.AcquireNullInt64()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}

func init() {
	condition.RegisterScanner(parentParentScanner)
	ParentParent.ID = condition.NewField[models.ParentParent, model.UUID]("ID", "", "", parentParentScanner)
	ParentParent.Name = condition.NewStringField[models.ParentParent]("Name", "", "", parentParentScanner)
	ParentParent.Number = condition.NewNumericField[models.ParentParent, int]("Number", "", "", parentParentScanner)
}
