// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

var personScanner = &condition.Scanner[models.Person]{
	AssignValues: func(dest *models.Person, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				condition.ReleaseUUID(values[i])
			case "name":
				condition.ReleaseNullString(values[i])
			default:
				condition.ReleaseNullSink(values[i])
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireUUID()
			case "name":
				values[i] = condition.AcquireNullString()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}

func init() {
	condition.RegisterScanner(personScanner)
	Person.ID = condition.NewField[models.Person, model.UUID]("ID", "", "", personScanner)
	Person.Name = condition.NewStringField[models.Person]("Name", "", "", personScanner)
}
