// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

type personConditions struct {
	ID   condition.Field[models.Person, model.UUID]
	Name condition.StringField[models.Person]
}

var Person = personConditions{
	ID:   condition.NewField[models.Person, model.UUID]("ID", "", ""),
	Name: condition.NewStringField[models.Person]("Name", "", ""),
}

// Preload allows preloading the Person when doing a query
func (personConditions personConditions) preload() condition.Condition[models.Person] {
	return condition.NewPreloadCondition[models.Person](personConditions.ID, personConditions.Name)
}
