// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

var phoneNoTimestampsScanner = &condition.Scanner[models.PhoneNoTimestamps]{
	AssignValues: func(dest *models.PhoneNoTimestamps, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = model.UIntID(v.Int64)
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			case "brand_id":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner brand_id: bad type %T", values[i])
				}
				if v.Valid {
					dest.BrandID = uint(v.Int64)
				}
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "name":
				if v, ok := values[i].(*sql.NullString); ok {
					condition.ReleaseNullString(v)
				}
			case "brand_id":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			default:
				if v, ok := values[i].(*condition.NullSink); ok {
					condition.ReleaseNullSink(v)
				}
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireNullInt64()
			case "name":
				values[i] = condition.AcquireNullString()
			case "brand_id":
				values[i] = condition.AcquireNullInt64()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}
var phoneNoTimestampsBrandJoinScanner = &condition.RelationScanner[models.PhoneNoTimestamps, models.Brand]{
	ChildScanner: brandScanner,
	Mount: func(p *models.PhoneNoTimestamps, c *models.Brand) {
		p.Brand = *c
	},
	RelationField: "Brand",
}

func init() {
	condition.RegisterScanner(phoneNoTimestampsScanner)
	PhoneNoTimestamps.ID = condition.NewField[models.PhoneNoTimestamps, model.UIntID]("ID", "", "", phoneNoTimestampsScanner)
	PhoneNoTimestamps.Name = condition.NewStringField[models.PhoneNoTimestamps]("Name", "", "", phoneNoTimestampsScanner)
	PhoneNoTimestamps.BrandID = condition.NewNumericField[models.PhoneNoTimestamps, uint]("BrandID", "", "", phoneNoTimestampsScanner)
}
