// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

func (phoneNoTimestampsConditions phoneNoTimestampsConditions) Brand(conditions ...condition.Condition[models.Brand]) condition.JoinCondition[models.PhoneNoTimestamps] {
	return condition.NewJoinCondition[models.PhoneNoTimestamps, models.Brand](conditions, "Brand", "BrandID", phoneNoTimestampsConditions.preload(), "ID", Brand.preload())
}

type phoneNoTimestampsConditions struct {
	ID      condition.Field[models.PhoneNoTimestamps, model.UIntID]
	Name    condition.StringField[models.PhoneNoTimestamps]
	BrandID condition.NumericField[models.PhoneNoTimestamps, uint]
}

var PhoneNoTimestamps = phoneNoTimestampsConditions{
	BrandID: condition.NewNumericField[models.PhoneNoTimestamps, uint]("BrandID", "", ""),
	ID:      condition.NewField[models.PhoneNoTimestamps, model.UIntID]("ID", "", ""),
	Name:    condition.NewStringField[models.PhoneNoTimestamps]("Name", "", ""),
}

// Preload allows preloading the PhoneNoTimestamps when doing a query
func (phoneNoTimestampsConditions phoneNoTimestampsConditions) preload() condition.Condition[models.PhoneNoTimestamps] {
	return condition.NewPreloadCondition[models.PhoneNoTimestamps](phoneNoTimestampsConditions.ID, phoneNoTimestampsConditions.Name, phoneNoTimestampsConditions.BrandID)
}
