// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
	gorm "gorm.io/gorm"
	"time"
)

var phoneScanner = &condition.Scanner[models.Phone]{
	AssignValues: func(dest *models.Phone, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = model.UIntID(v.Int64)
			case "created_at":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner created_at: bad type %T", values[i])
				}
				if v.Valid {
					dest.CreatedAt = v.Time
				}
			case "updated_at":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner updated_at: bad type %T", values[i])
				}
				if v.Valid {
					dest.UpdatedAt = v.Time
				}
			case "deleted_at":
				v, ok := values[i].(*gorm.DeletedAt)
				if !ok {
					return fmt.Errorf("cql scanner deleted_at: bad type %T", values[i])
				}
				dest.DeletedAt = *v
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			case "brand_id":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner brand_id: bad type %T", values[i])
				}
				if v.Valid {
					dest.BrandID = uint(v.Int64)
				}
			}
		}
		return nil
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = new(sql.NullInt64)
			case "created_at":
				values[i] = new(sql.NullTime)
			case "updated_at":
				values[i] = new(sql.NullTime)
			case "deleted_at":
				values[i] = new(gorm.DeletedAt)
			case "name":
				values[i] = new(sql.NullString)
			case "brand_id":
				values[i] = new(sql.NullInt64)
			default:
				values[i] = new(condition.NullSink)
			}
		}
		return values, nil
	},
}
var phoneBrandJoinScanner = &condition.RelationScanner[models.Phone, models.Brand]{
	ChildScanner: brandScanner,
	Mount: func(p *models.Phone, c *models.Brand) {
		p.Brand = *c
	},
	RelationField: "Brand",
}

func init() {
	Phone.ID = condition.NewField[models.Phone, model.UIntID]("ID", "", "", phoneScanner)
	Phone.CreatedAt = condition.NewField[models.Phone, time.Time]("CreatedAt", "", "", phoneScanner)
	Phone.UpdatedAt = condition.NewField[models.Phone, time.Time]("UpdatedAt", "", "", phoneScanner)
	Phone.DeletedAt = condition.NewField[models.Phone, time.Time]("DeletedAt", "", "", phoneScanner)
	Phone.Name = condition.NewStringField[models.Phone]("Name", "", "", phoneScanner)
	Phone.BrandID = condition.NewNumericField[models.Phone, uint]("BrandID", "", "", phoneScanner)
}
