// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
	gorm "gorm.io/gorm"
	"time"
)

var productScanner = &condition.Scanner[models.Product]{
	AssignValues: func(dest *models.Product, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "created_at":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner created_at: bad type %T", values[i])
				}
				if v.Valid {
					dest.CreatedAt = v.Time
				}
			case "updated_at":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner updated_at: bad type %T", values[i])
				}
				if v.Valid {
					dest.UpdatedAt = v.Time
				}
			case "deleted_at":
				v, ok := values[i].(*gorm.DeletedAt)
				if !ok {
					return fmt.Errorf("cql scanner deleted_at: bad type %T", values[i])
				}
				dest.DeletedAt = *v
			case "string_something_else":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner string_something_else: bad type %T", values[i])
				}
				if v.Valid {
					dest.String = v.String
				}
			case "int":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner int: bad type %T", values[i])
				}
				if v.Valid {
					dest.Int = int(v.Int64)
				}
			case "int_pointer":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner int_pointer: bad type %T", values[i])
				}
				if v.Valid {
					tmp := int(v.Int64)
					dest.IntPointer = &tmp
				} else {
					dest.IntPointer = nil
				}
			case "float":
				v, ok := values[i].(*sql.NullFloat64)
				if !ok {
					return fmt.Errorf("cql scanner float: bad type %T", values[i])
				}
				if v.Valid {
					dest.Float = v.Float64
				}
			case "null_float":
				v, ok := values[i].(*sql.NullFloat64)
				if !ok {
					return fmt.Errorf("cql scanner null_float: bad type %T", values[i])
				}
				dest.NullFloat = *v
			case "bool":
				v, ok := values[i].(*sql.NullBool)
				if !ok {
					return fmt.Errorf("cql scanner bool: bad type %T", values[i])
				}
				if v.Valid {
					dest.Bool = v.Bool
				}
			case "null_bool":
				v, ok := values[i].(*sql.NullBool)
				if !ok {
					return fmt.Errorf("cql scanner null_bool: bad type %T", values[i])
				}
				dest.NullBool = *v
			case "byte_array":
				v, ok := values[i].(*[]byte)
				if !ok {
					return fmt.Errorf("cql scanner byte_array: bad type %T", values[i])
				}
				dest.ByteArray = *v
			case "multi_string":
				w, ok := values[i].(*condition.NullableScanner)
				if !ok {
					return fmt.Errorf("cql scanner multi_string: bad wrapper type %T", values[i])
				}
				v, ok2 := w.Inner.(*models.MultiString)
				if !ok2 {
					return fmt.Errorf("cql scanner multi_string: bad inner type %T", w.Inner)
				}
				dest.MultiString = *v
			case "embedded_int":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner embedded_int: bad type %T", values[i])
				}
				if v.Valid {
					dest.EmbeddedInt = int(v.Int64)
				}
			case "gorm_embedded_int":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner gorm_embedded_int: bad type %T", values[i])
				}
				if v.Valid {
					dest.GormEmbedded.Int = int(v.Int64)
				}
			case "string2":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner string2: bad type %T", values[i])
				}
				if v.Valid {
					dest.String2 = v.String
				}
			}
		}
		return nil
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = new(model.UUID)
			case "created_at":
				values[i] = new(sql.NullTime)
			case "updated_at":
				values[i] = new(sql.NullTime)
			case "deleted_at":
				values[i] = new(gorm.DeletedAt)
			case "string_something_else":
				values[i] = new(sql.NullString)
			case "int":
				values[i] = new(sql.NullInt64)
			case "int_pointer":
				values[i] = new(sql.NullInt64)
			case "float":
				values[i] = new(sql.NullFloat64)
			case "null_float":
				values[i] = new(sql.NullFloat64)
			case "bool":
				values[i] = new(sql.NullBool)
			case "null_bool":
				values[i] = new(sql.NullBool)
			case "byte_array":
				values[i] = new([]byte)
			case "multi_string":
				values[i] = &condition.NullableScanner{Inner: new(models.MultiString)}
			case "embedded_int":
				values[i] = new(sql.NullInt64)
			case "gorm_embedded_int":
				values[i] = new(sql.NullInt64)
			case "string2":
				values[i] = new(sql.NullString)
			default:
				values[i] = new(condition.NullSink)
			}
		}
		return values, nil
	},
}

func init() {
	Product.ID = condition.NewField[models.Product, model.UUID]("ID", "", "", productScanner)
	Product.CreatedAt = condition.NewField[models.Product, time.Time]("CreatedAt", "", "", productScanner)
	Product.UpdatedAt = condition.NewField[models.Product, time.Time]("UpdatedAt", "", "", productScanner)
	Product.DeletedAt = condition.NewField[models.Product, time.Time]("DeletedAt", "", "", productScanner)
	Product.String = condition.NewStringField[models.Product]("String", "string_something_else", "", productScanner)
	Product.Int = condition.NewNumericField[models.Product, int]("Int", "", "", productScanner)
	Product.IntPointer = condition.NewNullableNumericField[models.Product, int]("IntPointer", "", "", productScanner)
	Product.Float = condition.NewNumericField[models.Product, float64]("Float", "", "", productScanner)
	Product.NullFloat = condition.NewNullableNumericField[models.Product, float64]("NullFloat", "", "", productScanner)
	Product.Bool = condition.NewBoolField[models.Product]("Bool", "", "", productScanner)
	Product.NullBool = condition.NewNullableBoolField[models.Product]("NullBool", "", "", productScanner)
	Product.ByteArray = condition.NewUpdatableField[models.Product, []uint8]("ByteArray", "", "", productScanner)
	Product.MultiString = condition.NewUpdatableField[models.Product, models.MultiString]("MultiString", "", "", productScanner)
	Product.ToBeEmbeddedEmbeddedInt = condition.NewNumericField[models.Product, int]("EmbeddedInt", "", "", productScanner)
	Product.GormEmbeddedInt = condition.NewNumericField[models.Product, int]("Int", "", "gorm_embedded_", productScanner)
	Product.String2 = condition.NewStringField[models.Product]("String2", "", "", productScanner)
}
