// Code generated by cql-cli v0.0.0, DO NOT EDIT.
package conditions

import (
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
	"time"
)

type productConditions struct {
	ID                      condition.Field[models.Product, model.UUID]
	CreatedAt               condition.Field[models.Product, time.Time]
	UpdatedAt               condition.Field[models.Product, time.Time]
	DeletedAt               condition.Field[models.Product, time.Time]
	String                  condition.StringField[models.Product]
	Int                     condition.Field[models.Product, int]
	IntPointer              condition.Field[models.Product, int]
	Float                   condition.Field[models.Product, float64]
	NullFloat               condition.Field[models.Product, float64]
	Bool                    condition.BoolField[models.Product]
	NullBool                condition.BoolField[models.Product]
	ByteArray               condition.Field[models.Product, []uint8]
	MultiString             condition.Field[models.Product, models.MultiString]
	ToBeEmbeddedEmbeddedInt condition.Field[models.Product, int]
	GormEmbeddedInt         condition.Field[models.Product, int]
}

var Product = productConditions{
	Bool:      condition.BoolField[models.Product]{Field: condition.Field[models.Product, bool]{Name: "Bool"}},
	ByteArray: condition.Field[models.Product, []uint8]{Name: "ByteArray"},
	CreatedAt: condition.Field[models.Product, time.Time]{Name: "CreatedAt"},
	DeletedAt: condition.Field[models.Product, time.Time]{Name: "DeletedAt"},
	Float:     condition.Field[models.Product, float64]{Name: "Float"},
	GormEmbeddedInt: condition.Field[models.Product, int]{
		ColumnPrefix: "gorm_embedded_",
		Name:         "Int",
	},
	ID:          condition.Field[models.Product, model.UUID]{Name: "ID"},
	Int:         condition.Field[models.Product, int]{Name: "Int"},
	IntPointer:  condition.Field[models.Product, int]{Name: "IntPointer"},
	MultiString: condition.Field[models.Product, models.MultiString]{Name: "MultiString"},
	NullBool:    condition.BoolField[models.Product]{Field: condition.Field[models.Product, bool]{Name: "NullBool"}},
	NullFloat:   condition.Field[models.Product, float64]{Name: "NullFloat"},
	String: condition.StringField[models.Product]{Field: condition.Field[models.Product, string]{
		Column: "string_something_else",
		Name:   "String",
	}},
	ToBeEmbeddedEmbeddedInt: condition.Field[models.Product, int]{Name: "EmbeddedInt"},
	UpdatedAt:               condition.Field[models.Product, time.Time]{Name: "UpdatedAt"},
}

// Preload allows preloading the Product when doing a query
func (productConditions productConditions) Preload() condition.Condition[models.Product] {
	return condition.NewPreloadCondition[models.Product](productConditions.ID, productConditions.CreatedAt, productConditions.UpdatedAt, productConditions.DeletedAt, productConditions.String, productConditions.Int, productConditions.IntPointer, productConditions.Float, productConditions.NullFloat, productConditions.Bool, productConditions.NullBool, productConditions.ByteArray, productConditions.MultiString, productConditions.ToBeEmbeddedEmbeddedInt, productConditions.GormEmbeddedInt)
}
