// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
	gorm "gorm.io/gorm"
	"time"
)

var saleScanner = &condition.Scanner[models.Sale]{
	AssignValues: func(dest *models.Sale, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "created_at":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner created_at: bad type %T", values[i])
				}
				if v.Valid {
					dest.CreatedAt = v.Time
				}
			case "updated_at":
				v, ok := values[i].(*sql.NullTime)
				if !ok {
					return fmt.Errorf("cql scanner updated_at: bad type %T", values[i])
				}
				if v.Valid {
					dest.UpdatedAt = v.Time
				}
			case "deleted_at":
				v, ok := values[i].(*gorm.DeletedAt)
				if !ok {
					return fmt.Errorf("cql scanner deleted_at: bad type %T", values[i])
				}
				dest.DeletedAt = *v
			case "code":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner code: bad type %T", values[i])
				}
				if v.Valid {
					dest.Code = int(v.Int64)
				}
			case "description":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner description: bad type %T", values[i])
				}
				if v.Valid {
					dest.Description = v.String
				}
			case "product_id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner product_id: bad type %T", values[i])
				}
				dest.ProductID = *v
			case "seller_id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner seller_id: bad type %T", values[i])
				}
				if *v == model.NilUUID {
					dest.SellerID = nil
				} else {
					tmp := *v
					dest.SellerID = &tmp
				}
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				if v, ok := values[i].(*model.UUID); ok {
					condition.ReleaseUUID(v)
				}
			case "created_at":
				if v, ok := values[i].(*sql.NullTime); ok {
					condition.ReleaseNullTime(v)
				}
			case "updated_at":
				if v, ok := values[i].(*sql.NullTime); ok {
					condition.ReleaseNullTime(v)
				}
			case "deleted_at":
				if v, ok := values[i].(*gorm.DeletedAt); ok {
					condition.ReleaseDeletedAt(v)
				}
			case "code":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "description":
				if v, ok := values[i].(*sql.NullString); ok {
					condition.ReleaseNullString(v)
				}
			case "product_id":
				if v, ok := values[i].(*model.UUID); ok {
					condition.ReleaseUUID(v)
				}
			case "seller_id":
				if v, ok := values[i].(*model.UUID); ok {
					condition.ReleaseUUID(v)
				}
			default:
				if v, ok := values[i].(*condition.NullSink); ok {
					condition.ReleaseNullSink(v)
				}
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireUUID()
			case "created_at":
				values[i] = condition.AcquireNullTime()
			case "updated_at":
				values[i] = condition.AcquireNullTime()
			case "deleted_at":
				values[i] = condition.AcquireDeletedAt()
			case "code":
				values[i] = condition.AcquireNullInt64()
			case "description":
				values[i] = condition.AcquireNullString()
			case "product_id":
				values[i] = condition.AcquireUUID()
			case "seller_id":
				values[i] = condition.AcquireUUID()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}
var saleProductJoinScanner = &condition.RelationScanner[models.Sale, models.Product]{
	ChildScanner: productScanner,
	Mount: func(p *models.Sale, c *models.Product) {
		p.Product = *c
	},
	RelationField: "Product",
}
var saleSellerJoinScanner = &condition.RelationScanner[models.Sale, models.Seller]{
	ChildScanner: sellerScanner,
	Mount: func(p *models.Sale, c *models.Seller) {
		p.Seller = c
	},
	RelationField: "Seller",
	SetNil: func(p *models.Sale) {
		p.Seller = nil
	},
}

func init() {
	condition.RegisterScanner(saleScanner)
	Sale.ID = condition.NewField[models.Sale, model.UUID]("ID", "", "", saleScanner)
	Sale.CreatedAt = condition.NewField[models.Sale, time.Time]("CreatedAt", "", "", saleScanner)
	Sale.UpdatedAt = condition.NewField[models.Sale, time.Time]("UpdatedAt", "", "", saleScanner)
	Sale.DeletedAt = condition.NewField[models.Sale, time.Time]("DeletedAt", "", "", saleScanner)
	Sale.Code = condition.NewNumericField[models.Sale, int]("Code", "", "", saleScanner)
	Sale.Description = condition.NewStringField[models.Sale]("Description", "", "", saleScanner)
	Sale.ProductID = condition.NewUpdatableField[models.Sale, model.UUID]("ProductID", "", "", saleScanner)
	Sale.SellerID = condition.NewNullableField[models.Sale, model.UUID]("SellerID", "", "", saleScanner)
}
