// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

func (saleNoTimestampsConditions saleNoTimestampsConditions) Product(conditions ...condition.Condition[models.ProductNoTimestamps]) condition.JoinCondition[models.SaleNoTimestamps] {
	return condition.NewJoinCondition[models.SaleNoTimestamps, models.ProductNoTimestamps](conditions, "Product", "ProductID", saleNoTimestampsConditions.preload(), "ID", ProductNoTimestamps.preload())
}
func (saleNoTimestampsConditions saleNoTimestampsConditions) Seller(conditions ...condition.Condition[models.SellerNoTimestamps]) condition.JoinCondition[models.SaleNoTimestamps] {
	return condition.NewJoinCondition[models.SaleNoTimestamps, models.SellerNoTimestamps](conditions, "Seller", "SellerID", saleNoTimestampsConditions.preload(), "ID", SellerNoTimestamps.preload())
}

type saleNoTimestampsConditions struct {
	ID          condition.Field[models.SaleNoTimestamps, model.UUID]
	Code        condition.NumericField[models.SaleNoTimestamps, int]
	Description condition.StringField[models.SaleNoTimestamps]
	ProductID   condition.UpdatableField[models.SaleNoTimestamps, model.UUID]
	SellerID    condition.NullableField[models.SaleNoTimestamps, model.UUID]
}

var SaleNoTimestamps = saleNoTimestampsConditions{
	Code:        condition.NewNumericField[models.SaleNoTimestamps, int]("Code", "", ""),
	Description: condition.NewStringField[models.SaleNoTimestamps]("Description", "", ""),
	ID:          condition.NewField[models.SaleNoTimestamps, model.UUID]("ID", "", ""),
	ProductID:   condition.NewUpdatableField[models.SaleNoTimestamps, model.UUID]("ProductID", "", ""),
	SellerID:    condition.NewNullableField[models.SaleNoTimestamps, model.UUID]("SellerID", "", ""),
}

// Preload allows preloading the SaleNoTimestamps when doing a query
func (saleNoTimestampsConditions saleNoTimestampsConditions) preload() condition.Condition[models.SaleNoTimestamps] {
	return condition.NewPreloadCondition[models.SaleNoTimestamps](saleNoTimestampsConditions.ID, saleNoTimestampsConditions.Code, saleNoTimestampsConditions.Description, saleNoTimestampsConditions.ProductID, saleNoTimestampsConditions.SellerID)
}
