// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

var saleNoTimestampsScanner = &condition.Scanner[models.SaleNoTimestamps]{
	AssignValues: func(dest *models.SaleNoTimestamps, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "code":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner code: bad type %T", values[i])
				}
				if v.Valid {
					dest.Code = int(v.Int64)
				}
			case "description":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner description: bad type %T", values[i])
				}
				if v.Valid {
					dest.Description = v.String
				}
			case "product_id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner product_id: bad type %T", values[i])
				}
				dest.ProductID = *v
			case "seller_id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner seller_id: bad type %T", values[i])
				}
				if *v == model.NilUUID {
					dest.SellerID = nil
				} else {
					tmp := *v
					dest.SellerID = &tmp
				}
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				if v, ok := values[i].(*model.UUID); ok {
					condition.ReleaseUUID(v)
				}
			case "code":
				if v, ok := values[i].(*sql.NullInt64); ok {
					condition.ReleaseNullInt64(v)
				}
			case "description":
				if v, ok := values[i].(*sql.NullString); ok {
					condition.ReleaseNullString(v)
				}
			case "product_id":
				if v, ok := values[i].(*model.UUID); ok {
					condition.ReleaseUUID(v)
				}
			case "seller_id":
				if v, ok := values[i].(*model.UUID); ok {
					condition.ReleaseUUID(v)
				}
			default:
				if v, ok := values[i].(*condition.NullSink); ok {
					condition.ReleaseNullSink(v)
				}
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireUUID()
			case "code":
				values[i] = condition.AcquireNullInt64()
			case "description":
				values[i] = condition.AcquireNullString()
			case "product_id":
				values[i] = condition.AcquireUUID()
			case "seller_id":
				values[i] = condition.AcquireUUID()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}

func init() {
	condition.RegisterScanner(saleNoTimestampsScanner)
}

var saleNoTimestampsProductJoinScanner = &condition.RelationScanner[models.SaleNoTimestamps, models.ProductNoTimestamps]{
	ChildScanner: productNoTimestampsScanner,
	Mount: func(p *models.SaleNoTimestamps, c *models.ProductNoTimestamps) {
		p.Product = *c
	},
	RelationField: "Product",
}
var saleNoTimestampsSellerJoinScanner = &condition.RelationScanner[models.SaleNoTimestamps, models.SellerNoTimestamps]{
	ChildScanner: sellerNoTimestampsScanner,
	Mount: func(p *models.SaleNoTimestamps, c *models.SellerNoTimestamps) {
		p.Seller = c
	},
	RelationField: "Seller",
	SetNil: func(p *models.SaleNoTimestamps) {
		p.Seller = nil
	},
}

func init() {
	SaleNoTimestamps.ID = condition.NewField[models.SaleNoTimestamps, model.UUID]("ID", "", "", saleNoTimestampsScanner)
	SaleNoTimestamps.Code = condition.NewNumericField[models.SaleNoTimestamps, int]("Code", "", "", saleNoTimestampsScanner)
	SaleNoTimestamps.Description = condition.NewStringField[models.SaleNoTimestamps]("Description", "", "", saleNoTimestampsScanner)
	SaleNoTimestamps.ProductID = condition.NewUpdatableField[models.SaleNoTimestamps, model.UUID]("ProductID", "", "", saleNoTimestampsScanner)
	SaleNoTimestamps.SellerID = condition.NewNullableField[models.SaleNoTimestamps, model.UUID]("SellerID", "", "", saleNoTimestampsScanner)
}
