// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

func (sellerNoTimestampsConditions sellerNoTimestampsConditions) CompanyNoTimestamps(conditions ...condition.Condition[models.CompanyNoTimestamps]) condition.JoinCondition[models.SellerNoTimestamps] {
	return condition.NewJoinCondition[models.SellerNoTimestamps, models.CompanyNoTimestamps](conditions, "CompanyNoTimestamps", "CompanyNoTimestampsID", sellerNoTimestampsConditions.preload(), "ID", CompanyNoTimestamps.preload())
}
func (sellerNoTimestampsConditions sellerNoTimestampsConditions) University(conditions ...condition.Condition[models.University]) condition.JoinCondition[models.SellerNoTimestamps] {
	return condition.NewJoinCondition[models.SellerNoTimestamps, models.University](conditions, "University", "UniversityID", sellerNoTimestampsConditions.preload(), "ID", University.preload())
}

type sellerNoTimestampsConditions struct {
	ID                    condition.Field[models.SellerNoTimestamps, model.UUID]
	Name                  condition.StringField[models.SellerNoTimestamps]
	CompanyNoTimestampsID condition.NullableField[models.SellerNoTimestamps, model.UUID]
	UniversityID          condition.NullableField[models.SellerNoTimestamps, model.UUID]
}

var SellerNoTimestamps = sellerNoTimestampsConditions{
	CompanyNoTimestampsID: condition.NewNullableField[models.SellerNoTimestamps, model.UUID]("CompanyNoTimestampsID", "", ""),
	ID:                    condition.NewField[models.SellerNoTimestamps, model.UUID]("ID", "", ""),
	Name:                  condition.NewStringField[models.SellerNoTimestamps]("Name", "", ""),
	UniversityID:          condition.NewNullableField[models.SellerNoTimestamps, model.UUID]("UniversityID", "", ""),
}

// Preload allows preloading the SellerNoTimestamps when doing a query
func (sellerNoTimestampsConditions sellerNoTimestampsConditions) preload() condition.Condition[models.SellerNoTimestamps] {
	return condition.NewPreloadCondition[models.SellerNoTimestamps](sellerNoTimestampsConditions.ID, sellerNoTimestampsConditions.Name, sellerNoTimestampsConditions.CompanyNoTimestampsID, sellerNoTimestampsConditions.UniversityID)
}
