// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

var sellerScanner = &condition.Scanner[models.Seller]{
	AssignValues: func(dest *models.Seller, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			case "company_id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner company_id: bad type %T", values[i])
				}
				if *v == model.NilUUID {
					dest.CompanyID = nil
				} else {
					tmp := *v
					dest.CompanyID = &tmp
				}
			case "university_id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner university_id: bad type %T", values[i])
				}
				if *v == model.NilUUID {
					dest.UniversityID = nil
				} else {
					tmp := *v
					dest.UniversityID = &tmp
				}
			}
		}
		return nil
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = new(model.UUID)
			case "name":
				values[i] = new(sql.NullString)
			case "company_id":
				values[i] = new(model.UUID)
			case "university_id":
				values[i] = new(model.UUID)
			default:
				values[i] = new(condition.NullSink)
			}
		}
		return values, nil
	},
}
var sellerCompanyJoinScanner = &condition.RelationScanner[models.Seller, models.Company]{
	ChildScanner: companyScanner,
	Mount: func(p *models.Seller, c *models.Company) {
		p.Company = c
	},
	RelationField: "Company",
	SetNil: func(p *models.Seller) {
		p.Company = nil
	},
}
var sellerUniversityJoinScanner = &condition.RelationScanner[models.Seller, models.University]{
	ChildScanner: universityScanner,
	Mount: func(p *models.Seller, c *models.University) {
		p.University = c
	},
	RelationField: "University",
	SetNil: func(p *models.Seller) {
		p.University = nil
	},
}

func init() {
	Seller.ID = condition.NewField[models.Seller, model.UUID]("ID", "", "", sellerScanner)
	Seller.Name = condition.NewStringField[models.Seller]("Name", "", "", sellerScanner)
	Seller.CompanyID = condition.NewNullableField[models.Seller, model.UUID]("CompanyID", "", "", sellerScanner)
	Seller.UniversityID = condition.NewNullableField[models.Seller, model.UUID]("UniversityID", "", "", sellerScanner)
}
