// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

var sellerNoTimestampsScanner = &condition.Scanner[models.SellerNoTimestamps]{
	AssignValues: func(dest *models.SellerNoTimestamps, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = *v
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			case "company_no_timestamps_id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner company_no_timestamps_id: bad type %T", values[i])
				}
				if *v == model.NilUUID {
					dest.CompanyNoTimestampsID = nil
				} else {
					tmp := *v
					dest.CompanyNoTimestampsID = &tmp
				}
			case "university_id":
				v, ok := values[i].(*model.UUID)
				if !ok {
					return fmt.Errorf("cql scanner university_id: bad type %T", values[i])
				}
				if *v == model.NilUUID {
					dest.UniversityID = nil
				} else {
					tmp := *v
					dest.UniversityID = &tmp
				}
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				condition.ReleaseUUID(values[i])
			case "name":
				condition.ReleaseNullString(values[i])
			case "company_no_timestamps_id":
				condition.ReleaseUUID(values[i])
			case "university_id":
				condition.ReleaseUUID(values[i])
			default:
				condition.ReleaseNullSink(values[i])
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireUUID()
			case "name":
				values[i] = condition.AcquireNullString()
			case "company_no_timestamps_id":
				values[i] = condition.AcquireUUID()
			case "university_id":
				values[i] = condition.AcquireUUID()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}
var sellerNoTimestampsCompanyNoTimestampsJoinScanner = &condition.RelationScanner[models.SellerNoTimestamps, models.CompanyNoTimestamps]{
	ChildScanner: companyNoTimestampsScanner,
	Mount: func(p *models.SellerNoTimestamps, c *models.CompanyNoTimestamps) {
		p.CompanyNoTimestamps = c
	},
	RelationField: "CompanyNoTimestamps",
	SetNil: func(p *models.SellerNoTimestamps) {
		p.CompanyNoTimestamps = nil
	},
}
var sellerNoTimestampsUniversityJoinScanner = &condition.RelationScanner[models.SellerNoTimestamps, models.University]{
	ChildScanner: universityScanner,
	Mount: func(p *models.SellerNoTimestamps, c *models.University) {
		p.University = c
	},
	RelationField: "University",
	SetNil: func(p *models.SellerNoTimestamps) {
		p.University = nil
	},
}

func init() {
	condition.RegisterScanner(sellerNoTimestampsScanner)
	SellerNoTimestamps.ID = condition.NewField[models.SellerNoTimestamps, model.UUID]("ID", "", "", sellerNoTimestampsScanner)
	SellerNoTimestamps.Name = condition.NewStringField[models.SellerNoTimestamps]("Name", "", "", sellerNoTimestampsScanner)
	SellerNoTimestamps.CompanyNoTimestampsID = condition.NewNullableField[models.SellerNoTimestamps, model.UUID]("CompanyNoTimestampsID", "", "", sellerNoTimestampsScanner)
	SellerNoTimestamps.UniversityID = condition.NewNullableField[models.SellerNoTimestamps, model.UUID]("UniversityID", "", "", sellerNoTimestampsScanner)
}
