// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	models "github.com/FrancoLiberali/cql/test/models"
)

type withUnsupportedColumnConditions struct {
	ID   condition.Field[models.WithUnsupportedColumn, model.UUID]
	Name condition.StringField[models.WithUnsupportedColumn]
}

var WithUnsupportedColumn = withUnsupportedColumnConditions{
	ID:   condition.NewField[models.WithUnsupportedColumn, model.UUID]("ID", "", ""),
	Name: condition.NewStringField[models.WithUnsupportedColumn]("Name", "", ""),
}

// Preload allows preloading the WithUnsupportedColumn when doing a query
func (withUnsupportedColumnConditions withUnsupportedColumnConditions) preload() condition.Condition[models.WithUnsupportedColumn] {
	return condition.NewPreloadCondition[models.WithUnsupportedColumn](withUnsupportedColumnConditions.ID, withUnsupportedColumnConditions.Name)
}
