// Code generated by badaas-cli v0.0.0, DO NOT EDIT.
package models

import orm "github.com/ditrit/badaas/orm"

func (m Bicycle) GetOwner() (*Person, error) {
	return orm.VerifyStructLoaded[Person](&m.Owner)
}
func (m Child) GetParent1() (*Parent1, error) {
	return orm.VerifyStructLoaded[Parent1](&m.Parent1)
}
func (m Child) GetParent2() (*Parent2, error) {
	return orm.VerifyStructLoaded[Parent2](&m.Parent2)
}
func (m City) GetCountry() (*Country, error) {
	return orm.VerifyPointerWithIDLoaded[Country](m.CountryID, m.Country)
}
func (m Country) GetCapital() (*City, error) {
	return orm.VerifyStructLoaded[City](&m.Capital)
}
func (m Employee) GetBoss() (*Employee, error) {
	return orm.VerifyPointerLoaded[Employee](m.BossID, m.Boss)
}
func (m Parent1) GetParentParent() (*ParentParent, error) {
	return orm.VerifyStructLoaded[ParentParent](&m.ParentParent)
}
func (m Parent2) GetParentParent() (*ParentParent, error) {
	return orm.VerifyStructLoaded[ParentParent](&m.ParentParent)
}
func (m Phone) GetBrand() (*Brand, error) {
	return orm.VerifyStructLoaded[Brand](&m.Brand)
}
func (m Sale) GetProduct() (*Product, error) {
	return orm.VerifyStructLoaded[Product](&m.Product)
}
func (m Sale) GetSeller() (*Seller, error) {
	return orm.VerifyPointerLoaded[Seller](m.SellerID, m.Seller)
}
func (m Seller) GetCompany() (*Company, error) {
	return orm.VerifyPointerLoaded[Company](m.CompanyID, m.Company)
}
