// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	verdeter "github.com/ditrit/verdeter"
	mock "github.com/stretchr/testify/mock"
)

// CommandInitializer is an autogenerated mock type for the CommandInitializer type
type CommandInitializer struct {
	mock.Mock
}

// Init provides a mock function with given fields: command
func (_m *CommandInitializer) Init(command *verdeter.VerdeterCommand) error {
	ret := _m.Called(command)

	var r0 error
	if rf, ok := ret.Get(0).(func(*verdeter.VerdeterCommand) error); ok {
		r0 = rf(command)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCommandInitializer interface {
	mock.TestingT
	Cleanup(func())
}

// NewCommandInitializer creates a new instance of CommandInitializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommandInitializer(t mockConstructorTestingTNewCommandInitializer) *CommandInitializer {
	mock := &CommandInitializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
