name: gen
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - cql-gen/**

jobs:
  check-style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          only-new-issues: true
          working-directory: cql-gen
          args: --config=../.golangci.yml
          skip-cache: true
          skip-save-cache: true

  test:
    name: Test
    needs: [check-style]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
          cache: true
      - name: Run tests
        run: go test ./cql-gen/tests -coverpkg=./cql-gen/... -coverprofile=coverage_gen.out -v
      - uses: actions/upload-artifact@v3
        with:
          name: coverage_gen
          path: coverage_gen.out