name: lint
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - cqllint/**

jobs:
  check-style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: go.sum
      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          only-new-issues: true
          working-directory: cqllint
          args: --config=../.golangci.yml
          skip-cache: true
          skip-save-cache: true

  test:
    name: Test
    needs: [check-style]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Mod download
        run: go mod download
      - name: Mod download cqllint
        run: go mod download
        working-directory: cqllint
      - name: Mod download testdata
        run: go mod download
        working-directory: cqllint/pkg/analyzer/testdata
      - name: Run tests
        run: GOPROXY=direct go test ./cqllint/... -coverpkg=./cqllint/... -coverprofile=coverage_lint.out -v
      - uses: actions/upload-artifact@v4
        with:
          name: coverage_lint
          path: coverage_lint.out